import type { Product, Review, GalleryShot } from './types'
import { asset } from './format'

const g = (label: string, zoom: number, pos: string): GalleryShot => ({ label, zoom, pos })
const STD: GalleryShot[] = [
  g('Front', 1, '50% 50%'),
  g('Detail', 1.85, '50% 62%'),
  g('Controls', 2.4, '50% 72%'),
  g('Profile', 1.3, '38% 45%'),
]

let rid = 0
const rv = (
  author: string, location: string, rating: number, title: string, body: string,
  date: string, verified = true,
): Review => ({ id: `r${++rid}`, author, location, rating, title, body, date, verified })

export const CATEGORIES = [
  'Kitchen', 'Laundry', 'Cooling', 'Home Entertainment', 'Small Appliances',
] as const

export const products: Product[] = [
  {
    id: 'p1',
    slug: 'nyota-glass-jug-blender-1800w',
    name: 'Nyota 1800W Glass Jug Blender',
    tagline: 'Crushes ice, groundnuts and matooke with equal calm.',
    brand: 'Nyota',
    category: 'Kitchen',
    price: 289000,
    compareAt: 349000,
    image: asset('/products/blender.webp'),
    gallery: STD,
    badges: ['Bestseller'],
    rating: 4.7,
    reviewCount: 214,
    stock: 26,
    warrantyMonths: 24,
    powerWatts: 1800,
    capacity: '1.8 L',
    colour: 'Brushed Steel',
    featured: true,
    bestseller: true,
    description:
      'A workhorse for the Ugandan kitchen. The 1800W copper-wound motor and six-point stainless blade assembly turn dry groundnuts into fine paste and ice into snow without straining. The thermal-shock resistant glass jug takes hot soup straight off the stove, and the whole assembly breaks down in seconds for washing.',
    highlights: [
      '1800W copper-wound motor with thermal overload protection',
      'Thermal-shock resistant 1.8L glass jug — safe for hot liquids',
      '6-point hardened stainless blade for ice, nuts and grains',
      'Variable speed dial plus pulse and smoothie presets',
      'Stabilised 220–240V operation, tolerant of grid fluctuation',
    ],
    specs: [
      { label: 'Power', value: '1800 W' },
      { label: 'Jug capacity', value: '1.8 L borosilicate glass' },
      { label: 'Speeds', value: 'Variable dial + Pulse + 2 presets' },
      { label: 'Blade', value: '6-point hardened stainless steel' },
      { label: 'Voltage', value: '220–240V / 50Hz' },
      { label: 'Warranty', value: '24 months' },
    ],
    reviews: [
      rv('Sarah Nakato', 'Ntinda, Kampala', 5, 'Finally one that survives groundnuts',
        'I have burnt through three blenders making odii. This one has been going eight months, twice a week, no smell of burning motor. The glass jug is heavy in a reassuring way.', '2026-06-14'),
      rv('Emmanuel Okello', 'Gulu', 5, 'Ice, no problem',
        'Bought for our bar in Gulu. We crush ice all evening on weekends and it keeps up. Delivery took three days upcountry which was fair.', '2026-05-02'),
      rv('Aisha Namuli', 'Kira', 4, 'Loud but excellent',
        'It does the job perfectly, my only complaint is the noise at top speed. Wakes the baby. Otherwise the smoothie preset is what I use every morning.', '2026-07-21'),
      rv('Denis Ssebugwawo', 'Masaka', 5, 'Warranty was honoured',
        'The coupler cracked at month five. Chikwafu replaced the part free, no argument. That is why I will buy from them again.', '2026-03-30'),
    ],
  },
  {
    id: 'p2',
    slug: 'kabira-30l-digital-microwave',
    name: 'Kabira 30L Digital Microwave Oven',
    tagline: 'Reheat, defrost and grill without the guesswork.',
    brand: 'Kabira',
    category: 'Kitchen',
    price: 749000,
    compareAt: 869000,
    image: asset('/products/microwave.webp'),
    gallery: STD,
    badges: ['Free Kampala delivery'],
    rating: 4.5,
    reviewCount: 138,
    stock: 14,
    warrantyMonths: 24,
    powerWatts: 900,
    capacity: '30 L',
    colour: 'Black Stainless',
    featured: true,
    description:
      'A generous 30 litre cavity that swallows a full family serving dish, with a quartz grill element for browning. Ten power levels, eight auto-cook programmes tuned for local staples, and a child lock. The interior is easy-clean enamel rather than paint, so posho splatter wipes off instead of staining.',
    highlights: [
      '30L cavity fits a full 32cm serving dish',
      'Quartz grill element for browning and crisping',
      '8 auto-cook programmes including rice, cassava and reheat',
      'Easy-clean enamel interior, not painted steel',
      'Child safety lock and 60-minute timer',
    ],
    specs: [
      { label: 'Capacity', value: '30 L' },
      { label: 'Microwave power', value: '900 W' },
      { label: 'Grill power', value: '1000 W quartz' },
      { label: 'Power levels', value: '10' },
      { label: 'Turntable', value: '315 mm glass' },
      { label: 'Warranty', value: '24 months' },
    ],
    reviews: [
      rv('Grace Atim', 'Bugolobi, Kampala', 5, 'Big enough for real dishes',
        'Most microwaves in the shops are 20 litres and my casserole dish will not fit. This one does. Grill is a bonus, I use it for cheese toast.', '2026-07-04'),
      rv('Ronald Kiggundu', 'Entebbe', 4, 'Good, panel is fiddly',
        'Heats evenly and looks smart on the counter. The touch panel needs a firm press, took me a week to get used to it.', '2026-06-19'),
      rv('Miriam Achieng', 'Jinja', 5, 'Wipes clean',
        'The inside really does clean easily which matters when the kids explode soup in it. Two years warranty gave me confidence.', '2026-04-11'),
    ],
  },
  {
    id: 'p3',
    slug: 'ssese-17l-cordless-kettle',
    name: 'Ssese 1.7L Cordless Kettle',
    tagline: 'Boils in three minutes, switches itself off.',
    brand: 'Ssese',
    category: 'Small Appliances',
    price: 129000,
    compareAt: 165000,
    image: asset('/products/kettle.webp'),
    gallery: STD,
    badges: ['Bestseller'],
    rating: 4.8,
    reviewCount: 402,
    stock: 68,
    warrantyMonths: 12,
    powerWatts: 2200,
    capacity: '1.7 L',
    colour: 'Brushed Steel',
    bestseller: true,
    featured: true,
    description:
      'Double-walled brushed stainless steel so the outside stays cool to touch. A concealed 2200W element heats 1.7 litres in about three minutes and shuts off automatically at boil, or if it is switched on dry. The 360° base means left- or right-handed pouring without fuss.',
    highlights: [
      'Boils 1.7L in roughly 3 minutes at 2200W',
      'Cool-touch double wall — safe around children',
      'Automatic shut-off at boil plus dry-boil protection',
      '360° cordless base, concealed element for easy descaling',
      'Washable limescale filter in the spout',
    ],
    specs: [
      { label: 'Capacity', value: '1.7 L' },
      { label: 'Power', value: '2200 W' },
      { label: 'Body', value: 'Double-wall stainless steel' },
      { label: 'Safety', value: 'Auto shut-off + dry-boil cut-out' },
      { label: 'Cord', value: '360° swivel base, storage well' },
      { label: 'Warranty', value: '12 months' },
    ],
    reviews: [
      rv('Patience Tumusiime', 'Mbarara', 5, 'Fast and quiet',
        'Three minutes flat for a full kettle. Outside stays cool which is the main reason I chose it, my toddler grabs everything.', '2026-08-01'),
      rv('Julius Wanyama', 'Mbale', 5, 'Two years on the same one at the office',
        'We have one at the office that has been boiling ten times a day since last year. Bought a second for home.', '2026-07-12'),
      rv('Nabukeera Faith', 'Kawempe', 5, 'Worth the price',
        'Cheaper kettles rust at the base after months. This one still looks new and descaling the filter takes a minute.', '2026-05-27'),
      rv('Tom Byaruhanga', 'Fort Portal', 4, 'Lid needs care',
        'Excellent kettle. The lid springs open quite fast so mind the steam. Boils beautifully though.', '2026-06-08'),
    ],
  },
  {
    id: 'p4',
    slug: 'kabira-55l-digital-air-fryer',
    name: 'Kabira 5.5L Digital Air Fryer',
    tagline: 'Crisp chips and chicken on a spoon of oil.',
    brand: 'Kabira',
    category: 'Kitchen',
    price: 419000,
    compareAt: 499000,
    image: asset('/products/airfryer.webp'),
    gallery: STD,
    badges: ['New'],
    rating: 4.6,
    reviewCount: 176,
    stock: 31,
    warrantyMonths: 18,
    powerWatts: 1500,
    capacity: '5.5 L',
    colour: 'Matte Black',
    featured: true,
    description:
      'Rapid hot-air circulation gives you the crunch of deep frying using a spoonful of oil. The 5.5 litre non-stick basket handles a whole chicken or chips for four. Eight presets cover chips, chicken, fish, samosas and reheat, and the basket is dishwasher safe.',
    highlights: [
      '5.5L basket — a whole chicken or chips for four',
      'Up to 85% less oil than deep frying',
      '8 presets including chips, chicken, fish and samosa',
      '80–200°C dial with 60-minute timer and auto shut-off',
      'Dishwasher-safe non-stick basket and crisping plate',
    ],
    specs: [
      { label: 'Capacity', value: '5.5 L' },
      { label: 'Power', value: '1500 W' },
      { label: 'Temperature', value: '80–200 °C' },
      { label: 'Presets', value: '8 programmes' },
      { label: 'Basket', value: 'Non-stick, dishwasher safe' },
      { label: 'Warranty', value: '18 months' },
    ],
    reviews: [
      rv('Brenda Kyomuhendo', 'Naalya', 5, 'My deep fryer is retired',
        'Chips come out properly crisp. I make samosas for the shop in it now and I am not going back to a sufuria of oil.', '2026-08-09'),
      rv('Ivan Muwanga', 'Kansanga', 4, 'Great, basket takes practice',
        'You must shake halfway or the bottom layer stays pale. Once you learn that it is brilliant. Cleaning is easy.', '2026-07-18'),
      rv('Rehema Nassuna', 'Wakiso', 5, 'Electricity friendly',
        'Uses less power than my oven and cooks faster. Good buy, and it arrived the same day I ordered.', '2026-06-25'),
    ],
  },
  {
    id: 'p5',
    slug: 'rwenzori-350l-double-door-fridge',
    name: 'Rwenzori 350L Double-Door Refrigerator',
    tagline: 'Frost-free cooling that rides out load-shedding.',
    brand: 'Rwenzori',
    category: 'Cooling',
    price: 2890000,
    compareAt: 3250000,
    image: asset('/products/fridge.webp'),
    gallery: STD,
    badges: ['Free installation'],
    rating: 4.6,
    reviewCount: 97,
    stock: 8,
    warrantyMonths: 60,
    powerWatts: 180,
    capacity: '350 L',
    colour: 'Silver',
    featured: true,
    description:
      'A 350 litre frost-free fridge-freezer built for real conditions. The inverter compressor holds temperature through voltage swings between 150V and 260V, and the insulated cabinet keeps food cold for up to twelve hours during an outage. Toughened glass shelves, a dedicated vegetable crisper, and a five-year compressor warranty.',
    highlights: [
      '350L total — 265L fridge, 85L freezer',
      'Inverter compressor stable from 150V to 260V',
      'Holds cold up to 12 hours during a power cut',
      'Frost-free: no more chipping ice out of the freezer',
      '5-year compressor warranty, free Kampala installation',
    ],
    specs: [
      { label: 'Total capacity', value: '350 L' },
      { label: 'Configuration', value: 'Top freezer, double door' },
      { label: 'Compressor', value: 'Inverter, 150–260V tolerant' },
      { label: 'Defrost', value: 'Frost-free' },
      { label: 'Energy use', value: '~0.9 kWh / 24h' },
      { label: 'Warranty', value: '24 months unit / 60 months compressor' },
    ],
    reviews: [
      rv('Robert Ssemakula', 'Munyonyo', 5, 'Survives our power',
        'Our line drops to about 170V in the evening. Old fridge kept cutting out, this one just runs. Cold stays overnight when UMEME goes.', '2026-05-16'),
      rv('Josephine Adongo', 'Lira', 4, 'Big and quiet',
        'Plenty of space for a family of six. Very quiet. Delivery to Lira took five days and they carried it inside, which I appreciated.', '2026-04-22'),
      rv('Hassan Mubiru', 'Kabalagala', 5, 'Freezer actually freezes',
        'Meat freezes hard within hours and no ice build-up after four months. Installation team was professional.', '2026-07-02'),
    ],
  },
  {
    id: 'p6',
    slug: 'rwenzori-8kg-front-load-washer',
    name: 'Rwenzori 8kg Front-Load Washing Machine',
    tagline: 'Fifteen programmes, gentle on water.',
    brand: 'Rwenzori',
    category: 'Laundry',
    price: 2450000,
    compareAt: 2790000,
    image: asset('/products/washer.webp'),
    gallery: STD,
    badges: ['Free installation'],
    rating: 4.4,
    reviewCount: 73,
    stock: 11,
    warrantyMonths: 36,
    powerWatts: 2000,
    capacity: '8 kg',
    colour: 'White',
    description:
      'An 8kg front loader with a brushless inverter motor — quieter, more efficient and rated for a decade of weekly washes. Fifteen programmes cover everything from a 15-minute quick wash to heavy bedding, and the 1200rpm spin leaves clothes nearly dry, which matters in the rainy season.',
    highlights: [
      '8kg drum — bedsheets, curtains and duvets welcome',
      'Brushless inverter motor with 10-year motor warranty',
      '15 programmes including 15-minute quick wash',
      '1200rpm spin leaves washing near dry for the rainy season',
      'Child lock and delayed start up to 24 hours',
    ],
    specs: [
      { label: 'Load capacity', value: '8 kg' },
      { label: 'Spin speed', value: '1200 rpm' },
      { label: 'Motor', value: 'Brushless inverter' },
      { label: 'Programmes', value: '15' },
      { label: 'Water use', value: '~48 L per full cycle' },
      { label: 'Warranty', value: '36 months / 10-year motor' },
    ],
    reviews: [
      rv('Catherine Nabbosa', 'Kyanja', 5, 'Rainy season saviour',
        'The 1200 spin is the reason I bought it. Clothes come out almost dry so they finish on the line even on a grey day.', '2026-06-30'),
      rv('Peter Odhiambo', 'Nakawa', 4, 'Quiet but needs level ground',
        'Very quiet once installed properly. It walked a bit on my uneven floor until the technician adjusted the feet.', '2026-05-09'),
      rv('Sylvia Kemigisha', 'Bushenyi', 4, 'Good machine, long cycles',
        'Cotton cycle takes nearly two hours. Results are excellent though and the quick wash handles most days.', '2026-07-27'),
    ],
  },
  {
    id: 'p7',
    slug: 'vista-55-inch-4k-smart-tv',
    name: 'Vista 55" 4K UHD Smart TV',
    tagline: 'Cinema-grade panel, built-in decoder-friendly tuner.',
    brand: 'Vista',
    category: 'Home Entertainment',
    price: 1990000,
    compareAt: 2350000,
    image: asset('/products/tv.webp'),
    gallery: STD,
    badges: ['Bestseller'],
    rating: 4.7,
    reviewCount: 261,
    stock: 19,
    warrantyMonths: 24,
    powerWatts: 120,
    capacity: '55 inch',
    colour: 'Black',
    featured: true,
    bestseller: true,
    description:
      'A 55-inch 4K panel with HDR10 and a near-invisible bezel. Built-in WiFi runs Netflix, YouTube and Showmax, while the integrated DVB-T2 tuner picks up free-to-air channels without an extra decoder box. Three HDMI inputs and eARC for a soundbar.',
    highlights: [
      '55" 4K UHD panel with HDR10 and 60Hz refresh',
      'Built-in DVB-T2 tuner — free-to-air without a decoder',
      'Netflix, YouTube, Showmax and Prime Video pre-installed',
      '3× HDMI (one eARC) and 2× USB for playback from a flash disk',
      'Wall-mountable, VESA 300×200',
    ],
    specs: [
      { label: 'Screen size', value: '55 inch diagonal' },
      { label: 'Resolution', value: '3840 × 2160 (4K UHD)' },
      { label: 'HDR', value: 'HDR10 / HLG' },
      { label: 'Tuner', value: 'DVB-T2 + DVB-S2' },
      { label: 'Connectivity', value: '3× HDMI, 2× USB, WiFi, LAN, Bluetooth' },
      { label: 'Warranty', value: '24 months' },
    ],
    reviews: [
      rv('Allan Kizza', 'Kireka', 5, 'Picture is superb',
        'Watched the whole league season on it. Colours are rich and football looks smooth. Free-to-air channels work without my old decoder.', '2026-08-05'),
      rv('Winnie Amongin', 'Soroti', 5, 'Delivered upcountry safely',
        'I was nervous ordering a TV online. It arrived double boxed with foam and not a scratch. Setup took ten minutes.', '2026-06-11'),
      rv('Fred Lubega', 'Makindye', 4, 'Speakers are only okay',
        'The panel is excellent for the money. Built-in speakers are thin, so I added a soundbar. With that it is perfect.', '2026-07-15'),
      rv('Doreen Kabuye', 'Mukono', 5, 'Smart apps are quick',
        'Netflix loads fast and the remote has shortcut buttons. No lag when switching apps, unlike my old smart TV.', '2026-05-20'),
    ],
  },
  {
    id: 'p8',
    slug: 'nyota-4-burner-gas-cooker-oven',
    name: 'Nyota 4-Burner Gas Cooker with Electric Oven',
    tagline: 'Cast-iron trivets, a real oven, one footprint.',
    brand: 'Nyota',
    category: 'Kitchen',
    price: 1750000,
    compareAt: 1990000,
    image: asset('/products/cooker.webp'),
    gallery: STD,
    badges: ['Free installation'],
    rating: 4.5,
    reviewCount: 84,
    stock: 9,
    warrantyMonths: 24,
    powerWatts: 2000,
    capacity: '60 cm',
    colour: 'Stainless Steel',
    description:
      'Four gas burners including a rapid wok ring sit under heavy cast-iron trivets that hold a sufuria steady. Below, a 60 litre electric oven with a grill element and double-glazed door. Flame failure devices cut the gas if a burner blows out — essential in a windy kitchen.',
    highlights: [
      '4 gas burners including a rapid 3.0kW wok ring',
      'Cast-iron trivets hold heavy sufurias steady',
      '60L electric oven with grill and rotisserie',
      'Flame failure safety device on every burner',
      'Double-glazed oven door and enamel easy-clean cavity',
    ],
    specs: [
      { label: 'Hob', value: '4 gas burners, cast-iron trivets' },
      { label: 'Oven', value: '60 L electric with grill' },
      { label: 'Width', value: '60 cm' },
      { label: 'Safety', value: 'Flame failure device, all burners' },
      { label: 'Ignition', value: 'One-hand electric spark' },
      { label: 'Warranty', value: '24 months' },
    ],
    reviews: [
      rv('Margaret Nakiwala', 'Seguku', 5, 'The oven is the win',
        'I bake cakes for sale and this oven holds temperature well. The cast iron stands take my biggest sufuria without wobbling.', '2026-07-08'),
      rv('Charles Ojok', 'Arua', 4, 'Solid build',
        'Heavy and well made. Installation was included which saved me hunting for a gas fitter. Oven takes a while to preheat.', '2026-04-29'),
      rv('Zainab Nakintu', 'Nsambya', 5, 'Flame cut-out reassures me',
        'My old cooker once filled the kitchen with gas when the wind blew a burner out. This one shuts off by itself.', '2026-06-02'),
    ],
  },
  {
    id: 'p9',
    slug: 'ssese-ceramic-steam-iron',
    name: 'Ssese Ceramic Soleplate Steam Iron',
    tagline: 'Glides, steams, and never drips on white cotton.',
    brand: 'Ssese',
    category: 'Small Appliances',
    price: 98000,
    compareAt: 125000,
    image: asset('/products/iron.webp'),
    gallery: STD,
    badges: [],
    rating: 4.4,
    reviewCount: 189,
    stock: 74,
    warrantyMonths: 12,
    powerWatts: 2400,
    capacity: '350 ml',
    colour: 'Teal',
    description:
      'A 2400W iron with a scratch-resistant ceramic soleplate that slides over cotton and kitenge without catching. Continuous steam plus a 180g burst shifts stubborn creases, and anti-drip means no water marks on a white shirt. Self-cleaning handles our hard water.',
    highlights: [
      '2400W with a scratch-resistant ceramic soleplate',
      '40g/min continuous steam, 180g vertical burst',
      'Anti-drip system — no water spots on light fabric',
      'Self-clean function for hard-water limescale',
      '350ml tank and 2.5m swivel cord',
    ],
    specs: [
      { label: 'Power', value: '2400 W' },
      { label: 'Soleplate', value: 'Ceramic non-stick' },
      { label: 'Steam output', value: '40 g/min continuous' },
      { label: 'Steam burst', value: '180 g' },
      { label: 'Water tank', value: '350 ml' },
      { label: 'Warranty', value: '12 months' },
    ],
    reviews: [
      rv('Esther Nagawa', 'Kawuku', 5, 'Kitenge comes out crisp',
        'Slides over kitenge beautifully and the vertical steam works on curtains while they hang. Good value.', '2026-07-23'),
      rv('Samuel Tugume', 'Kabale', 4, 'Heats very fast',
        'Ready in about thirty seconds. Cord could be a bit longer but it does everything I need for school uniforms.', '2026-06-17'),
      rv('Lydia Akello', 'Tororo', 4, 'No more brown marks',
        'My last iron kept spitting rusty water. This one has not dripped once in three months of use.', '2026-05-31'),
    ],
  },
  {
    id: 'p10',
    slug: 'kabira-18l-digital-rice-cooker',
    name: 'Kabira 1.8L Digital Rice Cooker & Steamer',
    tagline: 'Perfect rice, plus a steamer basket for matooke.',
    brand: 'Kabira',
    category: 'Kitchen',
    price: 189000,
    compareAt: 235000,
    image: asset('/products/ricecooker.webp'),
    gallery: STD,
    badges: ['New'],
    rating: 4.6,
    reviewCount: 121,
    stock: 43,
    warrantyMonths: 12,
    powerWatts: 700,
    capacity: '1.8 L',
    colour: 'Stainless Steel',
    description:
      'Ten cups of cooked rice, every grain separate, with automatic keep-warm for up to twelve hours. The stacking steamer basket handles matooke, cassava or vegetables above the rice, so one socket cooks two things. Non-stick inner pot lifts out for washing.',
    highlights: [
      'Cooks up to 10 cups, 1.8L non-stick inner pot',
      'Stacking steamer basket for matooke, cassava or greens',
      'Automatic keep-warm holds 12 hours',
      'Digital panel with rice, porridge, steam and slow-cook modes',
      'Detachable cord and removable steam vent for cleaning',
    ],
    specs: [
      { label: 'Capacity', value: '1.8 L / 10 cups cooked' },
      { label: 'Power', value: '700 W' },
      { label: 'Modes', value: 'Rice, porridge, steam, slow cook, reheat' },
      { label: 'Keep warm', value: 'Automatic, up to 12 hours' },
      { label: 'Inner pot', value: 'Removable non-stick' },
      { label: 'Warranty', value: '12 months' },
    ],
    reviews: [
      rv('Harriet Nambooze', 'Kyaliwajjala', 5, 'Rice never burns now',
        'I can start it and go bathe. Comes out the same every time and the keep-warm means supper is ready whenever people arrive.', '2026-08-12'),
      rv('Moses Kirya', 'Iganga', 5, 'Steamer basket is clever',
        'Rice below, matooke above, one plug. For a small kitchen that is a real saving.', '2026-07-01'),
      rv('Annet Birungi', 'Rubaga', 4, 'Pot needs gentle washing',
        'Excellent cooker. Just do not scrub the non-stick with steel wool like my house help did once.', '2026-06-06'),
    ],
  },
]

export const getProduct = (slug: string) => products.find((p) => p.slug === slug)

export const priceBounds = products.reduce(
  (acc, p) => ({ min: Math.min(acc.min, p.price), max: Math.max(acc.max, p.price) }),
  { min: Infinity, max: 0 },
)

export const brands = [...new Set(products.map((p) => p.brand))].sort()

export const collections = [
  {
    slug: 'kitchen',
    title: 'The Kitchen',
    blurb: 'Blenders, cookers, air fryers and everything between.',
    image: asset('/products/cooker.webp'),
    category: 'Kitchen' as const,
  },
  {
    slug: 'cooling',
    title: 'Cold Storage',
    blurb: 'Fridges built for Ugandan voltage and long outages.',
    image: asset('/products/fridge.webp'),
    category: 'Cooling' as const,
  },
  {
    slug: 'entertainment',
    title: 'The Living Room',
    blurb: '4K panels and sound that fills the sitting room.',
    image: asset('/products/tv.webp'),
    category: 'Home Entertainment' as const,
  },
  {
    slug: 'laundry',
    title: 'Laundry Day',
    blurb: 'Front loaders that spin dry before the rain comes.',
    image: asset('/products/washer.webp'),
    category: 'Laundry' as const,
  },
]
