import type { Product, Review, GalleryShot } from './types'
import { asset } from './format'

/**
 * Catalogue sourced from live Jumia Uganda listings (August 2026).
 * `compareAt` is the observed Jumia price; `price` is that figure plus the
 * 10% Chikwafu margin, rounded to the nearest 1,000 UGX.
 */

const STD: GalleryShot[] = [
  { label: 'Front', zoom: 1, pos: '50% 50%' },
  { label: 'Detail', zoom: 1.85, pos: '50% 62%' },
  { label: 'Controls', zoom: 2.4, pos: '50% 72%' },
  { label: 'Profile', zoom: 1.3, pos: '38% 45%' },
]

let rid = 0
const rv = (
  author: string, location: string, rating: number, title: string, body: string,
  date: string, verified = true,
): Review => ({ id: `r${++rid}`, author, location, rating, title, body, date, verified })

export const CATEGORIES = [
  'Kitchen', 'Laundry', 'Cooling', 'Home Entertainment', 'Small Appliances',
] as const

export const products: Product[] = [
  // ─────────────────────────── COOLING ───────────────────────────
  {
    id: 'p1',
    slug: 'hisense-270l-double-door-fridge-dispenser',
    name: 'Hisense 270L Double-Door Fridge with Water Dispenser',
    tagline: 'Chilled water on tap, no door opening required.',
    brand: 'Hisense',
    category: 'Cooling',
    price: 1045000,
    image: asset('/products/fridge-dispenser.webp'),
    gallery: STD,
    badges: ['Free installation'],
    rating: 4.5, reviewCount: 214, stock: 9,
    warrantyMonths: 36, powerWatts: 180, capacity: '270 L', colour: 'Silver',
    featured: true,
    description:
      'A 270 litre double-door fridge with an external water dispenser, so a cold glass costs you nothing in cooling. Defrost operation, toughened glass shelves and a vegetable crisper. Backed by a three-year Hisense warranty honoured locally.',
    highlights: [
      '270L total capacity — comfortable for a family of six',
      'External water dispenser, no need to open the door',
      'Defrost system with adjustable thermostat',
      'Toughened glass shelves and dedicated crisper',
      '3-year warranty, free Kampala installation',
    ],
    specs: [
      { label: 'Capacity', value: '270 L' },
      { label: 'Model', value: 'RD-27DR' },
      { label: 'Configuration', value: 'Double door, top freezer' },
      { label: 'Dispenser', value: 'External chilled water' },
      { label: 'Voltage', value: '220–240V / 50Hz' },
      { label: 'Warranty', value: '36 months' },
    ],
    reviews: [
      rv('Robert Ssemakula', 'Munyonyo', 5, 'The dispenser gets used all day',
        'With children in the house the fridge door was open every five minutes. Now they use the dispenser and the food stays properly cold.', '2026-07-16'),
      rv('Josephine Adongo', 'Lira', 4, 'Big and quiet',
        'Plenty of room and very quiet at night. Delivery to Lira took five days and they brought it inside.', '2026-06-22'),
      rv('Hassan Mubiru', 'Kabalagala', 5, 'Freezer actually freezes',
        'Meat is hard within hours. Four months in and no ice build-up on the shelves.', '2026-08-02'),
    ],
  },
  {
    id: 'p2',
    slug: 'hisense-160l-double-door-fridge',
    name: 'Hisense 160L Double-Door Refrigerator',
    tagline: 'The sensible size for a growing household.',
    brand: 'Hisense',
    category: 'Cooling',
    price: 768000,
    image: asset('/products/fridge.webp'),
    gallery: STD,
    badges: ['Bestseller'],
    rating: 4.4, reviewCount: 486, stock: 17,
    warrantyMonths: 36, powerWatts: 150, capacity: '160 L', colour: 'Silver',
    featured: true, bestseller: true,
    description:
      'A 160 litre double-door fridge that fits a small kitchen without giving up a separate freezer compartment. Defrost operation keeps running costs low and the reversible door suits either corner.',
    highlights: [
      '160L with a separate top freezer compartment',
      'Defrost operation — low running cost',
      'Reversible door hinge for tight kitchens',
      'Adjustable thermostat and toughened shelves',
      '3-year Hisense warranty',
    ],
    specs: [
      { label: 'Capacity', value: '160 L' },
      { label: 'Model', value: 'RD-16DR' },
      { label: 'Configuration', value: 'Double door' },
      { label: 'Defrost', value: 'Manual defrost' },
      { label: 'Voltage', value: '220–240V / 50Hz' },
      { label: 'Warranty', value: '36 months' },
    ],
    reviews: [
      rv('Grace Atim', 'Bugolobi', 5, 'Right size for two of us',
        'We did not need a huge fridge. This fits the corner of the kitchen and the freezer holds a week of meat.', '2026-07-09'),
      rv('Ronald Kiggundu', 'Entebbe', 4, 'Good value',
        'Cools well and is quiet. You must defrost it yourself every few weeks, which is the trade-off at this price.', '2026-05-30'),
    ],
  },
  {
    id: 'p3',
    slug: 'adh-276l-double-door-refrigerator',
    name: 'ADH 276L Double-Door Refrigerator',
    tagline: 'Serious cold storage for a big family.',
    brand: 'ADH',
    category: 'Cooling',
    price: 850000,
    image: asset('/products/fridge-single.webp'),
    gallery: STD,
    badges: [],
    rating: 4.2, reviewCount: 158, stock: 12,
    warrantyMonths: 36, powerWatts: 170, capacity: '276 L', colour: 'Silver',
    description:
      'At 276 litres this handles a full weekly shop for a large household, with a generous freezer above and adjustable shelving below. Three-year warranty on the sealed system.',
    highlights: [
      '276L — built for a large household',
      'Generous top freezer compartment',
      'Adjustable shelves and door balconies',
      'Stable operation on fluctuating mains',
      '3-year warranty',
    ],
    specs: [
      { label: 'Capacity', value: '276 L' },
      { label: 'Configuration', value: 'Double door, top freezer' },
      { label: 'Colour options', value: 'Silver / Blue / Black' },
      { label: 'Defrost', value: 'Manual defrost' },
      { label: 'Voltage', value: '220–240V / 50Hz' },
      { label: 'Warranty', value: '36 months' },
    ],
    reviews: [
      rv('Margaret Nakiwala', 'Seguku', 4, 'Holds a whole shop',
        'I cook for a big family and this takes everything from the market in one go. Solid for the money.', '2026-06-28'),
      rv('Charles Ojok', 'Arua', 4, 'Arrived safely upcountry',
        'Well packed and undamaged after the trip to Arua. Cooling is strong.', '2026-05-12'),
    ],
  },
  {
    id: 'p4',
    slug: 'pixel-120l-single-door-refrigerator',
    name: 'Pixel 120L Single-Door Refrigerator',
    tagline: 'Compact, affordable, and quiet enough for a bedsit.',
    brand: 'Pixel',
    category: 'Cooling',
    price: 373000,
    image: asset('/products/fridge-single.webp'),
    gallery: STD,
    badges: ['Bestseller'],
    rating: 3.8, reviewCount: 941, stock: 34,
    warrantyMonths: 12, powerWatts: 100, capacity: '120 L', colour: 'Silver',
    bestseller: true,
    description:
      'A 120 litre single-door fridge with a small internal freezer box — the standard choice for a hostel room, small flat or an office kitchen. Low power draw and quiet enough to sit in a bedroom.',
    highlights: [
      '120L single door with internal freezer box',
      'Low power draw, easy on a prepaid meter',
      'Quiet compressor — fine in a bedsit',
      'Adjustable thermostat',
      '1-year warranty',
    ],
    specs: [
      { label: 'Capacity', value: '120 L' },
      { label: 'Configuration', value: 'Single door' },
      { label: 'Freezer', value: 'Internal ice box' },
      { label: 'Defrost', value: 'Manual defrost' },
      { label: 'Voltage', value: '220–240V / 50Hz' },
      { label: 'Warranty', value: '12 months' },
    ],
    reviews: [
      rv('Ivan Muwanga', 'Kansanga', 4, 'Perfect for my flat',
        'Small kitchen, small budget. Keeps drinks cold and the ice box freezes properly.', '2026-07-25'),
      rv('Rehema Nassuna', 'Wakiso', 4, 'Quiet at night',
        'I was worried about noise in a one-room place but you barely hear it.', '2026-06-14'),
      rv('Denis Ssebugwawo', 'Masaka', 3, 'Does the job',
        'Fine for the price. The freezer box is small so do not expect to store much meat.', '2026-04-30'),
    ],
  },
  {
    id: 'p5',
    slug: 'adh-200l-chest-freezer',
    name: 'ADH 200L Chest Freezer',
    tagline: 'Bulk cold storage for the home or a small business.',
    brand: 'ADH',
    category: 'Cooling',
    price: 807000,
    image: asset('/products/chestfreezer.webp'),
    gallery: STD,
    badges: ['Free installation'],
    rating: 4.3, reviewCount: 176, stock: 10,
    warrantyMonths: 36, powerWatts: 200, capacity: '200 L', colour: 'White',
    description:
      'A 200 litre chest freezer with a sliding lid — the workhorse behind every duka selling cold drinks and every household that buys meat in bulk. Holds temperature for hours during an outage thanks to thick insulation.',
    highlights: [
      '200L capacity with sliding top lid',
      'Thick insulation holds cold through outages',
      'Removable storage basket and drain plug',
      'Suits home bulk storage or a small shop',
      '3-year warranty',
    ],
    specs: [
      { label: 'Capacity', value: '200 L' },
      { label: 'Lid', value: 'Sliding door' },
      { label: 'Colour options', value: 'White / Blue / Red' },
      { label: 'Defrost', value: 'Manual with drain plug' },
      { label: 'Voltage', value: '220–240V / 50Hz' },
      { label: 'Warranty', value: '36 months' },
    ],
    reviews: [
      rv('Sarah Nakato', 'Ntinda', 5, 'Bought it for the shop',
        'We sell cold sodas and this keeps up even when the door is opened all day. Paid for itself in a few months.', '2026-07-11'),
      rv('Emmanuel Okello', 'Gulu', 4, 'Stays cold when power goes',
        'Power here is unreliable. Things stay frozen through a whole evening outage.', '2026-06-03'),
    ],
  },

  // ─────────────────────────── KITCHEN ───────────────────────────
  {
    id: 'p6',
    slug: 'blueflame-50x50-3-gas-1-electric-cooker',
    name: 'Blueflame 50×50cm 3 Gas + 1 Electric Cooker',
    tagline: 'Turkish-built, with an electric oven that holds its heat.',
    brand: 'Blueflame',
    category: 'Kitchen',
    price: 646000,
    image: asset('/products/cooker.webp'),
    gallery: STD,
    badges: ['Free installation'],
    rating: 4.5, reviewCount: 263, stock: 11,
    warrantyMonths: 36, powerWatts: 2000, capacity: '50 × 50 cm', colour: 'Black',
    featured: true,
    description:
      'Made in Turkey, this 50×50cm cooker gives you three gas burners plus one electric hotplate, so you can still cook when the gas runs out mid-meal. The electric oven below holds temperature well enough for baking.',
    highlights: [
      '3 gas burners + 1 electric hotplate',
      'Electric oven with grill — genuinely bakes',
      'Made in Turkey, enamel easy-clean surfaces',
      'Cast trivets take a heavy sufuria',
      '3-year warranty, free Kampala installation',
    ],
    specs: [
      { label: 'Model', value: 'C5031E-B' },
      { label: 'Dimensions', value: '50 × 50 cm' },
      { label: 'Hob', value: '3 gas + 1 electric plate' },
      { label: 'Oven', value: 'Electric with grill' },
      { label: 'Origin', value: 'Made in Turkey' },
      { label: 'Warranty', value: '36 months' },
    ],
    reviews: [
      rv('Zainab Nakintu', 'Nsambya', 5, 'The electric plate saves me',
        'When the gas cylinder finishes at 8pm I just switch to the electric plate and finish supper. Best feature.', '2026-07-19'),
      rv('Harriet Nambooze', 'Kyaliwajjala', 4, 'Oven bakes evenly',
        'I bake cakes to sell and the oven holds its heat. Takes a while to preheat but the results are good.', '2026-06-08'),
      rv('Peter Odhiambo', 'Nakawa', 5, 'Solid build',
        'Heavy and well made, not the flimsy type. Installation was included.', '2026-05-21'),
    ],
  },
  {
    id: 'p7',
    slug: 'spj-50x50-3-gas-1-electric-cooker',
    name: 'SPJ 50×50cm 3 Gas + 1 Hotplate Cooker',
    tagline: 'A full standing cooker without the full price.',
    brand: 'SPJ',
    category: 'Kitchen',
    price: 402000,
    image: asset('/products/cooker-black.webp'),
    gallery: STD,
    badges: [],
    rating: 4.1, reviewCount: 342, stock: 19,
    warrantyMonths: 36, powerWatts: 1500, capacity: '50 × 50 cm', colour: 'Black',
    description:
      'The entry point into a proper standing cooker: three gas burners, an electric hotplate and a gas oven, in a 50×50cm footprint that fits most Kampala kitchens. Three-year warranty is unusual at this price.',
    highlights: [
      '3 gas burners + 1 electric hotplate',
      'Gas oven with viewing window',
      'Compact 50 × 50 cm footprint',
      'Enamel pan supports, easy to wipe',
      '3-year warranty',
    ],
    specs: [
      { label: 'Dimensions', value: '50 × 50 cm' },
      { label: 'Hob', value: '3 gas + 1 electric plate' },
      { label: 'Oven', value: 'Gas oven' },
      { label: 'Ignition', value: 'Manual' },
      { label: 'Voltage', value: '220–240V / 50Hz' },
      { label: 'Warranty', value: '36 months' },
    ],
    reviews: [
      rv('Annet Birungi', 'Rubaga', 4, 'Good starter cooker',
        'Moved out of my parents place and needed something affordable. Cooks fine, oven works.', '2026-08-04'),
      rv('Moses Kirya', 'Iganga', 4, 'Value for money',
        'Three years warranty at this price surprised me. No problems in four months.', '2026-06-17'),
    ],
  },
  {
    id: 'p8',
    slug: 'hisense-20l-manual-microwave',
    name: 'Hisense 20L Manual Microwave',
    tagline: 'Two dials, no menu diving.',
    brand: 'Hisense',
    category: 'Kitchen',
    price: 230000,
    image: asset('/products/microwave.webp'),
    gallery: STD,
    badges: [],
    rating: 4.3, reviewCount: 197, stock: 26,
    warrantyMonths: 24, powerWatts: 700, capacity: '20 L', colour: 'White',
    express: true,
    description:
      'A 20 litre microwave with two mechanical dials — power and timer. Nothing to learn, nothing to break, and no touch panel to stop responding. Ideal for reheating and defrosting.',
    highlights: [
      '20L cavity with 245mm turntable',
      'Mechanical dials — no fragile touch panel',
      '6 power levels and a 30-minute timer',
      'Defrost setting for meat and bread',
      '2-year Hisense warranty',
    ],
    specs: [
      { label: 'Capacity', value: '20 L' },
      { label: 'Model', value: 'H20MOMS10' },
      { label: 'Power', value: '700 W' },
      { label: 'Control', value: 'Mechanical dials' },
      { label: 'Turntable', value: '245 mm' },
      { label: 'Warranty', value: '24 months' },
    ],
    reviews: [
      rv('Miriam Achieng', 'Jinja', 4, 'Simple and it works',
        'My last microwave had a touch panel that died. This one has dials my mother can also use.', '2026-07-02'),
      rv('Fred Lubega', 'Makindye', 4, 'Small but fine',
        'Twenty litres is tight for a big dish but for reheating it is perfect.', '2026-05-26'),
    ],
  },
  {
    id: 'p9',
    slug: 'hoffmans-6l-touch-air-fryer',
    name: 'Hoffmans 6L Touch Screen Air Fryer',
    tagline: 'Chips and chicken on a spoonful of oil.',
    brand: 'Hoffmans',
    category: 'Kitchen',
    price: 121000,
    image: asset('/products/airfryer.webp'),
    gallery: STD,
    badges: ['New'],
    rating: 4.4, reviewCount: 231, stock: 41,
    warrantyMonths: 12, powerWatts: 1400, capacity: '6 L', colour: 'Black',
    featured: true,
    express: true,
    description:
      'A 6 litre oil-free air fryer with a touch screen and preset programmes. Rapid hot-air circulation crisps chips, chicken and samosas using a fraction of the oil — and a fraction of the power an oven would draw.',
    highlights: [
      '6L basket — chips or chicken for a family',
      'Up to 85% less oil than deep frying',
      'Touch screen with preset programmes',
      'Uses less power than heating a full oven',
      'Non-stick basket, easy to wash',
    ],
    specs: [
      { label: 'Capacity', value: '6 L' },
      { label: 'Model', value: 'HM-6018' },
      { label: 'Power', value: '1400 W' },
      { label: 'Control', value: 'Touch screen with presets' },
      { label: 'Temperature', value: '80–200 °C' },
      { label: 'Warranty', value: '12 months' },
    ],
    reviews: [
      rv('Brenda Kyomuhendo', 'Naalya', 5, 'My deep fryer is retired',
        'Chips come out properly crisp. I make samosas in it now and I am not going back to a sufuria of oil.', '2026-08-09'),
      rv('Esther Nagawa', 'Kawuku', 4, 'Shake it halfway',
        'You must shake the basket halfway or the bottom stays pale. Once you learn that it is brilliant.', '2026-07-18'),
      rv('Lydia Akello', 'Tororo', 4, 'Saves on power',
        'Cooks faster than my oven and the kitchen stays cool. Good buy.', '2026-06-25'),
    ],
  },
  {
    id: 'p10',
    slug: 'panda-350w-2in1-juice-blender',
    name: 'Panda 350W 1.75L 2-in-1 Juice Blender',
    tagline: 'Blends and grinds — avocado, mango, groundnuts.',
    brand: 'Panda',
    category: 'Kitchen',
    price: 53000,
    image: asset('/products/juiceblender.webp'),
    gallery: STD,
    badges: [],
    rating: 4.0, reviewCount: 287, stock: 52,
    warrantyMonths: 12, powerWatts: 350, capacity: '1.75 L', colour: 'Red',
    express: true,
    description:
      'A 350W blender with a 1.75 litre jug plus a dry mill attachment, so it handles smoothies and grinding in the same machine. Straightforward, affordable and easy to strip down for washing.',
    highlights: [
      '2-in-1: wet blending jug plus dry grinding mill',
      '1.75L jug with measurement markings',
      'Stainless steel blades, two speeds plus pulse',
      'Grinds groundnuts, simsim and dry spices',
      'Dishwasher-safe jug, easy to dismantle',
    ],
    specs: [
      { label: 'Power', value: '350 W' },
      { label: 'Jug capacity', value: '1.75 L' },
      { label: 'Attachments', value: 'Blending jug + dry mill' },
      { label: 'Speeds', value: '2 + pulse' },
      { label: 'Voltage', value: '220–240V / 50Hz' },
      { label: 'Warranty', value: '12 months' },
    ],
    reviews: [
      rv('Aisha Namuli', 'Kira', 4, 'The mill is the useful part',
        'I grind groundnuts for odii in the small jar. Do not overload it and it copes well.', '2026-07-21'),
      rv('Catherine Nabbosa', 'Kyanja', 4, 'Good for the price',
        'Smoothies every morning, no complaints. It is 350W so give it a rest between long runs.', '2026-06-12'),
    ],
  },
  {
    id: 'p11',
    slug: 'nyota-1800w-glass-jug-blender',
    name: 'Nyota 1800W Glass Jug Blender',
    tagline: 'Crushes ice and groundnuts without straining.',
    brand: 'Nyota',
    category: 'Kitchen',
    price: 289000,
    compareAt: 349000,
    image: asset('/products/blender.webp'),
    gallery: STD,
    badges: ['Bestseller'],
    rating: 4.7, reviewCount: 214, stock: 23,
    warrantyMonths: 24, powerWatts: 1800, capacity: '1.8 L', colour: 'Brushed Steel',
    bestseller: true, featured: true,
    express: true,
    description:
      'When a 350W machine is not enough: an 1800W copper-wound motor with a six-point blade and a thermal-shock resistant glass jug. Turns dry groundnuts into fine paste and ice into snow.',
    highlights: [
      '1800W copper-wound motor with overload protection',
      'Thermal-shock resistant glass jug — safe for hot soup',
      '6-point hardened stainless blade',
      'Variable speed dial plus pulse',
      'Tolerant of Ugandan grid fluctuation',
    ],
    specs: [
      { label: 'Power', value: '1800 W' },
      { label: 'Jug capacity', value: '1.8 L borosilicate glass' },
      { label: 'Speeds', value: 'Variable + Pulse' },
      { label: 'Blade', value: '6-point hardened stainless' },
      { label: 'Voltage', value: '220–240V / 50Hz' },
      { label: 'Warranty', value: '24 months' },
    ],
    reviews: [
      rv('Sarah Nakato', 'Ntinda', 5, 'Finally one that survives groundnuts',
        'I have burnt through three blenders making odii. Eight months on this one, twice a week, no smell of burning motor.', '2026-06-14'),
      rv('Emmanuel Okello', 'Gulu', 5, 'Ice, no problem',
        'Bought for our bar. We crush ice all evening on weekends and it keeps up.', '2026-05-02'),
    ],
  },
  {
    id: 'p12',
    slug: 'kabira-18l-digital-rice-cooker',
    name: 'Kabira 1.8L Digital Rice Cooker & Steamer',
    tagline: 'Rice below, matooke above, one socket.',
    brand: 'Kabira',
    category: 'Kitchen',
    price: 189000,
    compareAt: 235000,
    image: asset('/products/ricecooker.webp'),
    gallery: STD,
    badges: [],
    rating: 4.6, reviewCount: 121, stock: 38,
    warrantyMonths: 12, powerWatts: 700, capacity: '1.8 L', colour: 'Stainless Steel',
    express: true,
    description:
      'Ten cups of cooked rice with every grain separate, plus a stacking steamer basket for matooke, cassava or vegetables above. Automatic keep-warm holds supper for up to twelve hours.',
    highlights: [
      'Cooks up to 10 cups, 1.8L non-stick pot',
      'Stacking steamer basket for matooke or cassava',
      'Automatic keep-warm up to 12 hours',
      'Digital panel: rice, porridge, steam, slow cook',
      'Removable inner pot and steam vent',
    ],
    specs: [
      { label: 'Capacity', value: '1.8 L / 10 cups cooked' },
      { label: 'Power', value: '700 W' },
      { label: 'Modes', value: 'Rice, porridge, steam, slow cook' },
      { label: 'Keep warm', value: 'Automatic, 12 hours' },
      { label: 'Inner pot', value: 'Removable non-stick' },
      { label: 'Warranty', value: '12 months' },
    ],
    reviews: [
      rv('Harriet Nambooze', 'Kyaliwajjala', 5, 'Rice never burns now',
        'Start it and go bathe. Comes out the same every time and keep-warm means supper waits.', '2026-08-12'),
      rv('Moses Kirya', 'Iganga', 5, 'Steamer basket is clever',
        'Rice below, matooke above, one plug. For a small kitchen that is a real saving.', '2026-07-01'),
    ],
  },

  // ────────────────────── SMALL APPLIANCES ──────────────────────
  {
    id: 'p13',
    slug: 'roch-2l-fast-boiling-percolator',
    name: 'Roch 2L Fast-Boiling Percolator Kettle',
    tagline: 'Two litres of hot water with a tap on the front.',
    brand: 'Roch',
    category: 'Small Appliances',
    price: 19000,
    image: asset('/products/percolator.webp'),
    gallery: STD,
    badges: ['Bestseller'],
    rating: 4.1, reviewCount: 624, stock: 88,
    warrantyMonths: 12, powerWatts: 1000, capacity: '2 L', colour: 'Silver & Black',
    bestseller: true,
    express: true,
    description:
      'A 2 litre percolator with a spigot tap — fill it once in the morning and draw hot water for tea all day. The standard fixture in Ugandan offices and guest houses, and hard to beat at this price.',
    highlights: [
      '2L capacity with front spigot tap',
      'Keeps water hot for serving through the morning',
      'Stainless steel body with cool-touch handle',
      'Automatic cut-out and boil-dry protection',
      'Ideal for offices, guest houses and events',
    ],
    specs: [
      { label: 'Capacity', value: '2 L' },
      { label: 'Power', value: '1000 W' },
      { label: 'Dispensing', value: 'Front spigot tap' },
      { label: 'Body', value: 'Stainless steel' },
      { label: 'Safety', value: 'Auto cut-out, boil-dry protection' },
      { label: 'Warranty', value: '12 months' },
    ],
    reviews: [
      rv('Patience Tumusiime', 'Mbarara', 4, 'Office favourite',
        'One fill does the whole morning tea round. The tap saves everyone lifting a hot kettle.', '2026-08-01'),
      rv('Julius Wanyama', 'Mbale', 4, 'Cheap and useful',
        'At this price I bought two, one for home and one for the shop.', '2026-07-12'),
      rv('Tom Byaruhanga', 'Fort Portal', 4, 'Takes a while to boil',
        'It is 1000W so it is not instant, but it holds heat well once hot.', '2026-06-08'),
    ],
  },
  {
    id: 'p14',
    slug: 'ssese-17l-cordless-kettle',
    name: 'Ssese 1.7L Cordless Kettle',
    tagline: 'Boils in three minutes, switches itself off.',
    brand: 'Ssese',
    category: 'Small Appliances',
    price: 129000,
    compareAt: 165000,
    image: asset('/products/kettle.webp'),
    gallery: STD,
    badges: [],
    rating: 4.8, reviewCount: 402, stock: 61,
    warrantyMonths: 12, powerWatts: 2200, capacity: '1.7 L', colour: 'Brushed Steel',
    featured: true,
    express: true,
    description:
      'Double-walled brushed stainless steel so the outside stays cool to touch. A concealed 2200W element boils 1.7 litres in about three minutes and shuts off automatically at boil, or if switched on dry.',
    highlights: [
      'Boils 1.7L in roughly 3 minutes at 2200W',
      'Cool-touch double wall — safe around children',
      'Auto shut-off at boil plus dry-boil protection',
      '360° cordless base, concealed element',
      'Washable limescale filter',
    ],
    specs: [
      { label: 'Capacity', value: '1.7 L' },
      { label: 'Power', value: '2200 W' },
      { label: 'Body', value: 'Double-wall stainless steel' },
      { label: 'Safety', value: 'Auto shut-off + dry-boil cut-out' },
      { label: 'Base', value: '360° swivel' },
      { label: 'Warranty', value: '12 months' },
    ],
    reviews: [
      rv('Nabukeera Faith', 'Kawempe', 5, 'Worth the price',
        'Cheaper kettles rust at the base after months. This still looks new and descaling takes a minute.', '2026-05-27'),
      rv('Patience Tumusiime', 'Mbarara', 5, 'Fast and cool to touch',
        'Three minutes flat. The cool outside is why I chose it, my toddler grabs everything.', '2026-08-01'),
    ],
  },
  {
    id: 'p15',
    slug: 'ssese-ceramic-steam-iron',
    name: 'Ssese Ceramic Soleplate Steam Iron',
    tagline: 'Glides over kitenge, never drips on white cotton.',
    brand: 'Ssese',
    category: 'Small Appliances',
    price: 98000,
    compareAt: 125000,
    image: asset('/products/iron.webp'),
    gallery: STD,
    badges: [],
    rating: 4.4, reviewCount: 189, stock: 67,
    warrantyMonths: 12, powerWatts: 2400, capacity: '350 ml', colour: 'Teal',
    express: true,
    description:
      'A 2400W iron with a scratch-resistant ceramic soleplate that slides over cotton and kitenge without catching. Anti-drip means no water marks on a white shirt, and self-clean handles hard water.',
    highlights: [
      '2400W with scratch-resistant ceramic soleplate',
      '40g/min continuous steam, 180g vertical burst',
      'Anti-drip — no water spots on light fabric',
      'Self-clean for hard-water limescale',
      '350ml tank and 2.5m swivel cord',
    ],
    specs: [
      { label: 'Power', value: '2400 W' },
      { label: 'Soleplate', value: 'Ceramic non-stick' },
      { label: 'Steam output', value: '40 g/min' },
      { label: 'Steam burst', value: '180 g' },
      { label: 'Water tank', value: '350 ml' },
      { label: 'Warranty', value: '12 months' },
    ],
    reviews: [
      rv('Esther Nagawa', 'Kawuku', 5, 'Kitenge comes out crisp',
        'Slides over kitenge beautifully and the vertical steam works on hanging curtains.', '2026-07-23'),
      rv('Samuel Tugume', 'Kabale', 4, 'Heats very fast',
        'Ready in about thirty seconds. Cord could be longer but it handles school uniforms fine.', '2026-06-17'),
    ],
  },

  // ─────────────────────────── LAUNDRY ───────────────────────────
  {
    id: 'p16',
    slug: 'hisense-9kg-front-load-washing-machine',
    name: 'Hisense 9kg Automatic Front-Load Washing Machine',
    tagline: 'Fully automatic, and it spins almost dry.',
    brand: 'Hisense',
    category: 'Laundry',
    price: 1375000,
    image: asset('/products/frontload.webp'),
    gallery: STD,
    badges: ['Free installation'],
    rating: 4.5, reviewCount: 168, stock: 8,
    warrantyMonths: 24, powerWatts: 2000, capacity: '9 kg', colour: 'Silver',
    featured: true,
    description:
      'A 9kg fully automatic front loader — load it, choose a programme and walk away. The high-speed spin leaves washing nearly dry, which matters in the rainy season when line-drying is a gamble.',
    highlights: [
      '9kg drum — bedsheets, curtains and duvets',
      'Fully automatic: wash, rinse and spin unattended',
      'High-speed spin leaves washing near dry',
      'Multiple programmes including quick wash',
      '2-year Hisense warranty, free installation',
    ],
    specs: [
      { label: 'Load capacity', value: '9 kg' },
      { label: 'Type', value: 'Front loading, fully automatic' },
      { label: 'Programmes', value: 'Multiple including quick wash' },
      { label: 'Child lock', value: 'Yes' },
      { label: 'Voltage', value: '220–240V / 50Hz' },
      { label: 'Warranty', value: '24 months' },
    ],
    reviews: [
      rv('Catherine Nabbosa', 'Kyanja', 5, 'Rainy season saviour',
        'The spin is the reason I bought it. Clothes come out almost dry so they finish on the line even on a grey day.', '2026-06-30'),
      rv('Sylvia Kemigisha', 'Bushenyi', 4, 'Long cycles but excellent',
        'The cotton cycle takes nearly two hours. Results are excellent and quick wash handles most days.', '2026-07-27'),
    ],
  },
  {
    id: 'p17',
    slug: 'spj-10kg-twin-tub-washing-machine',
    name: 'SPJ 10kg Twin Tub Washing Machine',
    tagline: 'Wash and spin side by side — and you control the water.',
    brand: 'SPJ',
    category: 'Laundry',
    price: 635000,
    image: asset('/products/twintub.webp'),
    gallery: STD,
    badges: ['Bestseller'],
    rating: 4.2, reviewCount: 304, stock: 21,
    warrantyMonths: 60, powerWatts: 400, capacity: '10 kg', colour: 'White',
    bestseller: true,
    description:
      'The twin tub remains the practical choice where water supply is unreliable: you fill it yourself, wash a big 10kg load, then move it to the spinner. Far less water and power than an automatic, and a five-year warranty.',
    highlights: [
      '10kg wash capacity, separate spin tub',
      'Fill manually — works without mains water pressure',
      'Uses far less water and power than an automatic',
      'Reuse wash water across loads',
      '5-year warranty',
    ],
    specs: [
      { label: 'Wash capacity', value: '10 kg' },
      { label: 'Type', value: 'Twin tub, semi-automatic' },
      { label: 'Spin', value: 'Separate spin tub' },
      { label: 'Water supply', value: 'Manual fill' },
      { label: 'Power', value: '400 W' },
      { label: 'Warranty', value: '60 months' },
    ],
    reviews: [
      rv('Rehema Nassuna', 'Wakiso', 4, 'Better where water is a problem',
        'Our taps are dry half the week. I fill this from a jerrycan and it still works. An automatic could not.', '2026-07-14'),
      rv('Grace Atim', 'Bugolobi', 4, 'Big loads, low bills',
        'Ten kilos is a lot of washing and it barely moves the meter. You do have to lift clothes between tubs.', '2026-06-05'),
      rv('Josephine Adongo', 'Lira', 5, 'Five years warranty',
        'That warranty is why I chose it over a cheaper one. Working perfectly so far.', '2026-05-18'),
    ],
  },
  {
    id: 'p18',
    slug: 'pixel-8kg-twin-tub-washing-machine',
    name: 'Pixel 8kg Twin Tub Washing Machine',
    tagline: 'The affordable way to stop washing by hand.',
    brand: 'Pixel',
    category: 'Laundry',
    price: 549000,
    image: asset('/products/twintub.webp'),
    gallery: STD,
    badges: [],
    rating: 4.0, reviewCount: 213, stock: 24,
    warrantyMonths: 12, powerWatts: 380, capacity: '8 kg', colour: 'Grey',
    description:
      'An 8kg twin tub for households making the jump from hand washing. Manual fill, separate spinner, and light enough for one person to move out to the yard and back.',
    highlights: [
      '8kg wash capacity with separate spinner',
      'Light enough to move to the yard',
      'Manual fill — no plumbing needed',
      'Low power draw, prepaid-meter friendly',
      '1-year warranty',
    ],
    specs: [
      { label: 'Wash capacity', value: '8 kg' },
      { label: 'Type', value: 'Twin tub, semi-automatic' },
      { label: 'Spin', value: 'Separate spin tub' },
      { label: 'Water supply', value: 'Manual fill' },
      { label: 'Power', value: '380 W' },
      { label: 'Warranty', value: '12 months' },
    ],
    reviews: [
      rv('Annet Birungi', 'Rubaga', 4, 'Saved my hands',
        'After years of washing by hand this feels like luxury. Light enough to push outside.', '2026-07-30'),
      rv('Zainab Nakintu', 'Nsambya', 4, 'Does what it says',
        'Not fancy but it washes and spins. Good first machine.', '2026-06-20'),
    ],
  },

  // ────────────────────── HOME ENTERTAINMENT ──────────────────────
  {
    id: 'p19',
    slug: 'hisense-50-inch-smart-tv-50a4q',
    name: 'Hisense 50" 4K Smart TV (50A4Q)',
    tagline: 'A proper big screen, with three years of cover.',
    brand: 'Hisense',
    category: 'Home Entertainment',
    price: 1066000,
    image: asset('/products/tv.webp'),
    gallery: STD,
    badges: ['Bestseller'],
    rating: 4.6, reviewCount: 341, stock: 13,
    warrantyMonths: 36, powerWatts: 110, capacity: '50 inch', colour: 'Black',
    featured: true, bestseller: true,
    description:
      'A 50 inch smart panel running Netflix, YouTube and Showmax over built-in WiFi, with a free-to-air tuner so local channels work without an extra decoder. Three-year Hisense warranty honoured in Kampala.',
    highlights: [
      '50" 4K smart panel with built-in WiFi',
      'Netflix, YouTube and Showmax pre-installed',
      'Free-to-air tuner — no decoder box needed',
      'Multiple HDMI and USB inputs',
      '3-year warranty',
    ],
    specs: [
      { label: 'Screen size', value: '50 inch' },
      { label: 'Model', value: '50A4Q' },
      { label: 'Resolution', value: '4K UHD' },
      { label: 'Smart platform', value: 'VIDAA' },
      { label: 'Tuner', value: 'Built-in free-to-air' },
      { label: 'Warranty', value: '36 months' },
    ],
    reviews: [
      rv('Allan Kizza', 'Kireka', 5, 'Picture is superb',
        'Watched the whole league season on it. Football looks smooth and free-to-air works without my old decoder.', '2026-08-05'),
      rv('Winnie Amongin', 'Soroti', 5, 'Delivered upcountry safely',
        'Nervous ordering a TV online. Arrived double boxed with foam, not a scratch.', '2026-06-11'),
      rv('Doreen Kabuye', 'Mukono', 4, 'Apps are quick',
        'Netflix loads fast and no lag switching apps, unlike my old smart TV.', '2026-05-20'),
    ],
  },
  {
    id: 'p20',
    slug: 'tcl-43-inch-google-tv-s323',
    name: 'TCL 43" Bezel-Less HD Smart Google TV',
    tagline: 'Google TV, almost no bezel, sensible size.',
    brand: 'TCL',
    category: 'Home Entertainment',
    price: 836000,
    image: asset('/products/tv43.webp'),
    gallery: STD,
    badges: [],
    rating: 4.4, reviewCount: 126, stock: 16,
    warrantyMonths: 24, powerWatts: 90, capacity: '43 inch', colour: 'Black',
    description:
      'A 43 inch bezel-less panel running full Google TV, so the remote has a microphone and every app you would expect is on the store. The right size for a sitting room without dominating it.',
    highlights: [
      '43" bezel-less HD panel',
      'Full Google TV with voice remote',
      'Chromecast built in — cast from your phone',
      'Netflix, YouTube, Showmax and the Play Store',
      '2-year warranty',
    ],
    specs: [
      { label: 'Screen size', value: '43 inch' },
      { label: 'Model', value: 's323dg4knhfh' },
      { label: 'Smart platform', value: 'Google TV' },
      { label: 'Casting', value: 'Chromecast built-in' },
      { label: 'Design', value: 'Bezel-less' },
      { label: 'Warranty', value: '24 months' },
    ],
    reviews: [
      rv('Fred Lubega', 'Makindye', 4, 'Google TV is the difference',
        'Casting from the phone just works and the voice remote is genuinely useful for finding things.', '2026-07-15'),
      rv('Ivan Muwanga', 'Kansanga', 5, 'Looks expensive',
        'The thin bezel makes it look far pricier than it was. Picture is sharp.', '2026-06-26'),
    ],
  },
  {
    id: 'p21',
    slug: 'skyworth-43-inch-qled-google-tv',
    name: 'Skyworth 43" QLED Google TV',
    tagline: 'QLED colour at a 43-inch price.',
    brand: 'Skyworth',
    category: 'Home Entertainment',
    price: 782000,
    image: asset('/products/tv43.webp'),
    gallery: STD,
    badges: ['New'],
    rating: 4.3, reviewCount: 87, stock: 14,
    warrantyMonths: 36, powerWatts: 95, capacity: '43 inch', colour: 'Black',
    description:
      'A QLED panel at 43 inches, which means richer, more saturated colour than a standard LED — noticeable on football pitches and nature programmes. Runs Google TV, with a three-year warranty.',
    highlights: [
      '43" QLED panel — richer colour than standard LED',
      'Google TV with voice remote and Play Store',
      'Chromecast built in',
      'Free-to-air tuner included',
      '3-year warranty',
    ],
    specs: [
      { label: 'Screen size', value: '43 inch' },
      { label: 'Panel', value: 'QLED' },
      { label: 'Smart platform', value: 'Google TV' },
      { label: 'Casting', value: 'Chromecast built-in' },
      { label: 'Tuner', value: 'Free-to-air' },
      { label: 'Warranty', value: '36 months' },
    ],
    reviews: [
      rv('Allan Kizza', 'Kireka', 4, 'Colours pop',
        'You can see the difference from a normal LED, especially greens on the pitch.', '2026-08-08'),
      rv('Denis Ssebugwawo', 'Masaka', 4, 'Three years cover',
        'QLED plus three years warranty at this price is why I picked it.', '2026-07-03'),
    ],
  },
  {
    id: 'p22',
    slug: 'itel-43-inch-hd-smart-tv',
    name: 'Itel 43" HD Android Smart TV',
    tagline: 'Netflix and YouTube without the premium price.',
    brand: 'Itel',
    category: 'Home Entertainment',
    price: 549000,
    image: asset('/products/tv43.webp'),
    gallery: STD,
    badges: [],
    rating: 4.1, reviewCount: 194, stock: 27,
    warrantyMonths: 24, powerWatts: 85, capacity: '43 inch', colour: 'Black',
    description:
      'A 43 inch Android smart TV with Netflix and YouTube built in, aimed squarely at households who want a big smart screen without spending a million shillings. Two-year warranty.',
    highlights: [
      '43" HD Android smart panel',
      'Netflix and YouTube pre-installed',
      'WiFi built in, no decoder subscription needed',
      'HDMI and USB inputs for a flash disk',
      '2-year warranty',
    ],
    specs: [
      { label: 'Screen size', value: '43 inch' },
      { label: 'Resolution', value: 'HD' },
      { label: 'Smart platform', value: 'Android' },
      { label: 'Apps', value: 'Netflix, YouTube' },
      { label: 'Connectivity', value: 'WiFi, HDMI, USB' },
      { label: 'Warranty', value: '24 months' },
    ],
    reviews: [
      rv('Winnie Amongin', 'Soroti', 4, 'Good value big screen',
        'For half the price of the big brands we got a 43 inch that streams fine.', '2026-07-28'),
      rv('Samuel Tugume', 'Kabale', 4, 'Fine for the money',
        'Picture is HD not 4K, but at this price that is fair. Apps work well.', '2026-06-19'),
    ],
  },
  {
    id: 'p23',
    slug: 'hisense-32-inch-hdr-led-tv',
    name: 'Hisense 32" HDR LED Free-to-Air TV',
    tagline: 'The bedroom and shop-counter standard.',
    brand: 'Hisense',
    category: 'Home Entertainment',
    price: 351000,
    image: asset('/products/tv32.webp'),
    gallery: STD,
    badges: ['Bestseller'],
    rating: 3.8, reviewCount: 1264, stock: 45,
    warrantyMonths: 36, powerWatts: 60, capacity: '32 inch', colour: 'Black',
    bestseller: true,
    description:
      'A 32 inch HDR LED with a built-in free-to-air tuner — the default second TV for a bedroom, shop counter or salon. Three-year Hisense warranty and low enough power draw to run off a modest inverter.',
    highlights: [
      '32" HDR LED panel',
      'Built-in free-to-air digital tuner',
      'Low 60W draw — works on a small inverter',
      'HDMI and USB inputs',
      '3-year Hisense warranty',
    ],
    specs: [
      { label: 'Screen size', value: '32 inch' },
      { label: 'Model', value: '32A5200F' },
      { label: 'Panel', value: 'HDR LED' },
      { label: 'Tuner', value: 'Digital free-to-air' },
      { label: 'Power', value: '60 W' },
      { label: 'Warranty', value: '36 months' },
    ],
    reviews: [
      rv('Miriam Achieng', 'Jinja', 4, 'Second TV for the bedroom',
        'Exactly what we needed. Free channels work straight out of the box.', '2026-07-06'),
      rv('Tom Byaruhanga', 'Fort Portal', 4, 'Runs on my inverter',
        'Low power so it keeps going during outages on a small backup. That sold it for me.', '2026-06-01'),
      rv('Nabukeera Faith', 'Kawempe', 3, 'Basic but reliable',
        'Not smart, no apps. But for watching local channels it does the job and has not failed.', '2026-05-15'),
    ],
  },
  {
    id: 'p24',
    slug: 'mitech-40-inch-full-hd-tv',
    name: 'Mitech 40" Full HD LED TV with Decoder',
    tagline: 'Forty inches, full HD, inbuilt decoder.',
    brand: 'Mitech',
    category: 'Home Entertainment',
    price: 453000,
    image: asset('/products/tv43.webp'),
    gallery: STD,
    badges: [],
    rating: 4.0, reviewCount: 148, stock: 22,
    warrantyMonths: 24, powerWatts: 75, capacity: '40 inch', colour: 'Black',
    description:
      'A 40 inch Full HD panel with the decoder built in, so free-to-air channels need nothing more than an aerial. A sensible middle size between a 32 and a 43.',
    highlights: [
      '40" Full HD 1080p panel',
      'Inbuilt digital decoder — aerial and go',
      'HDMI and USB playback',
      'Wall mountable',
      '2-year warranty',
    ],
    specs: [
      { label: 'Screen size', value: '40 inch' },
      { label: 'Resolution', value: 'Full HD 1080p' },
      { label: 'Decoder', value: 'Inbuilt free-to-air' },
      { label: 'Inputs', value: 'HDMI, USB' },
      { label: 'Mount', value: 'VESA wall mountable' },
      { label: 'Warranty', value: '24 months' },
    ],
    reviews: [
      rv('Peter Odhiambo', 'Nakawa', 4, 'Right size for our sitting room',
        'Forty inches is the sweet spot for us. Full HD looks sharp from the sofa.', '2026-07-22'),
      rv('Sylvia Kemigisha', 'Bushenyi', 4, 'No decoder needed',
        'Plugged in the aerial and the channels were there. Simple.', '2026-06-09'),
    ],
  },

  // ───────────── SMALL APPLIANCES & KITCHEN (Jumia sourced) ─────────────
  {
    id: 'p25',
    slug: 'hoffmans-14in1-electric-pressure-cooker',
    name: 'Hoffmans 14-in-1 6L Digital Pressure Cooker',
    tagline: 'Pressure cooks, steams and air fries in one pot.',
    brand: 'Hoffmans',
    category: 'Kitchen',
    price: 199000,
    image: asset('/products/pressurecooker.webp'),
    gallery: STD,
    badges: ['Express'],
    rating: 4.4, reviewCount: 168, stock: 29,
    warrantyMonths: 12, powerWatts: 1000, capacity: '6 L', colour: 'Silver',
    express: true, featured: true,
    description:
      'Fourteen programmes in a single 6 litre pot: pressure cook beans in twenty minutes instead of two hours, steam matooke, slow cook, or drop in the basket and air fry. The obvious choice when kitchen space and gas money are both tight.',
    highlights: [
      'Beans and posho in a fraction of the gas',
      '14 programmes including steam, slow cook and fry',
      'Comes with steamer rack and deep fryer basket',
      'Keep-warm holds supper until people arrive',
      'Lid safety lock and pressure release valve',
    ],
    specs: [
      { label: 'Capacity', value: '6 L' },
      { label: 'Model', value: 'HM-718' },
      { label: 'Programmes', value: '14-in-1' },
      { label: 'Power', value: '1000 W' },
      { label: 'Included', value: 'Steamer rack + fryer basket' },
      { label: 'Warranty', value: '12 months' },
    ],
    reviews: [
      rv('Harriet Nambooze', 'Kyaliwajjala', 5, 'Beans in twenty minutes',
        'I used to soak beans overnight and still burn a whole cylinder. This does them in twenty minutes. It has changed how I cook.', '2026-08-14'),
      rv('Ivan Muwanga', 'Kansanga', 4, 'Read the manual first',
        'Fourteen programmes is a lot to learn. Once you know three of them it is excellent.', '2026-07-20'),
    ],
  },
  {
    id: 'p26',
    slug: 'adh-25in1-electric-pressure-cooker',
    name: 'ADH 25-in-1 6L Multipurpose Pressure Cooker',
    tagline: 'Twenty-five presets, one socket.',
    brand: 'ADH',
    category: 'Kitchen',
    price: 151000,
    image: asset('/products/pressurecooker.webp'),
    gallery: STD,
    badges: ['Express'],
    rating: 4.2, reviewCount: 97, stock: 33,
    warrantyMonths: 12, powerWatts: 1000, capacity: '6 L', colour: 'Black & Silver',
    express: true,
    description:
      'A 6 litre multipurpose cooker with twenty-five preset programmes covering rice, beans, meat, porridge, cake and yoghurt. Sealed pressure cooking cuts both time and gas consumption dramatically.',
    highlights: [
      '25 preset programmes on a single dial',
      '6L stainless inner pot, family sized',
      'Cuts cooking time and gas use on beans and meat',
      'Delay timer and automatic keep-warm',
      'Safety lock lid with pressure valve',
    ],
    specs: [
      { label: 'Capacity', value: '6 L' },
      { label: 'Programmes', value: '25-in-1' },
      { label: 'Power', value: '1000 W' },
      { label: 'Inner pot', value: 'Non-stick, removable' },
      { label: 'Voltage', value: '220–240V / 50Hz' },
      { label: 'Warranty', value: '12 months' },
    ],
    reviews: [
      rv('Rehema Nassuna', 'Wakiso', 4, 'Saves on charcoal',
        'We were spending a fortune on charcoal for beans. This pays for itself.', '2026-07-26'),
      rv('Moses Kirya', 'Iganga', 4, 'Good size for a family',
        'Six litres feeds all of us with leftovers. Solid build for the price.', '2026-06-30'),
    ],
  },
  {
    id: 'p27',
    slug: 'pixel-7l-electric-pressure-cooker',
    name: 'Pixel 7L Multi-Function Pressure Cooker',
    tagline: 'Seven litres — cook once, eat twice.',
    brand: 'Pixel',
    category: 'Kitchen',
    price: 185000,
    image: asset('/products/pressurecooker.webp'),
    gallery: STD,
    badges: [],
    rating: 4.1, reviewCount: 74, stock: 21,
    warrantyMonths: 12, powerWatts: 1200, capacity: '7 L', colour: 'Silver',
    description:
      'At seven litres this is the largest of our pressure cookers, sized for big households or anyone who batch-cooks at the weekend. Includes a steamer insert for cooking two things at once.',
    highlights: [
      '7L capacity — the largest in our range',
      'Multi-function: pressure, steam, slow cook, rice',
      'Steamer insert included',
      'Ideal for batch cooking at the weekend',
      'Automatic keep-warm',
    ],
    specs: [
      { label: 'Capacity', value: '7 L' },
      { label: 'Power', value: '1200 W' },
      { label: 'Functions', value: 'Pressure, steam, slow cook, rice' },
      { label: 'Included', value: 'Steamer insert' },
      { label: 'Voltage', value: '220–240V / 50Hz' },
      { label: 'Warranty', value: '12 months' },
    ],
    reviews: [
      rv('Margaret Nakiwala', 'Seguku', 4, 'Big enough for catering',
        'I cook for events sometimes and seven litres handles it. Sturdy pot.', '2026-08-06'),
    ],
  },
  {
    id: 'p28',
    slug: 'sonashi-25l-digital-microwave',
    name: 'Sonashi 25L Digital Microwave with Grill',
    tagline: 'Touch control, child lock, 1000W grill.',
    brand: 'Sonashi',
    category: 'Kitchen',
    price: 426000,
    image: asset('/products/microwave-digital.webp'),
    gallery: STD,
    badges: [],
    rating: 4.3, reviewCount: 58, stock: 12,
    warrantyMonths: 24, powerWatts: 1000, capacity: '25 L', colour: 'Black & White',
    description:
      'A 25 litre digital microwave with a 1000W grill element for browning, five power levels and a child safety lock. The pull-open door handle is easier than a push-button latch when your hands are full.',
    highlights: [
      '25L cavity with 1000W grill element',
      'Digital touch control with 5 power levels',
      'Child safety lock',
      'Pull-open door handle',
      'Fast heating and defrost programmes',
    ],
    specs: [
      { label: 'Capacity', value: '25 L' },
      { label: 'Model', value: 'SMO-925DG' },
      { label: 'Grill', value: '1000 W' },
      { label: 'Power levels', value: '5' },
      { label: 'Safety', value: 'Child lock' },
      { label: 'Warranty', value: '24 months' },
    ],
    reviews: [
      rv('Grace Atim', 'Bugolobi', 4, 'Grill actually browns',
        'Most microwave grills are useless. This one browns cheese properly.', '2026-07-13'),
    ],
  },
  {
    id: 'p29',
    slug: 'pixel-6l-oil-free-air-fryer',
    name: 'Pixel 6L Oil-Free Air Fryer',
    tagline: 'Same crunch, half the price.',
    brand: 'Pixel',
    category: 'Kitchen',
    price: 107000,
    image: asset('/products/airfryer-white.webp'),
    gallery: STD,
    badges: ['Express'],
    rating: 4.2, reviewCount: 212, stock: 46,
    warrantyMonths: 12, powerWatts: 1400, capacity: '6 L', colour: 'White & Grey',
    express: true,
    description:
      'A straightforward 6 litre air fryer with a temperature dial and timer rather than a touch screen — fewer things to fail, and cheaper for it. Same rapid hot-air crisping.',
    highlights: [
      '6L basket, family sized',
      'Simple dial controls, nothing to learn',
      'Oil-free crisping for chips and chicken',
      'Non-stick removable basket',
      '1-year warranty',
    ],
    specs: [
      { label: 'Capacity', value: '6 L' },
      { label: 'Power', value: '1400 W' },
      { label: 'Control', value: 'Temperature dial + timer' },
      { label: 'Temperature', value: '80–200 °C' },
      { label: 'Basket', value: 'Non-stick, removable' },
      { label: 'Warranty', value: '12 months' },
    ],
    reviews: [
      rv('Brenda Kyomuhendo', 'Naalya', 4, 'Cheaper and just as good',
        'I compared it with the touch screen one. Same chips, less money. Dials are easier anyway.', '2026-08-11'),
      rv('Annet Birungi', 'Rubaga', 4, 'Good first air fryer',
        'Wanted to try air frying without spending much. No regrets.', '2026-07-05'),
    ],
  },
  {
    id: 'p30',
    slug: 'hoffmans-22l-glass-led-kettle',
    name: 'Hoffmans 2.2L Glass Kettle with LED',
    tagline: 'Watch it boil, blue light and all.',
    brand: 'Hoffmans',
    category: 'Small Appliances',
    price: 44000,
    image: asset('/products/glasskettle.webp'),
    gallery: STD,
    badges: ['Express'],
    rating: 4.3, reviewCount: 143, stock: 58,
    warrantyMonths: 12, powerWatts: 1800, capacity: '2.2 L', colour: 'Transparent',
    express: true, featured: true,
    description:
      'A 2.2 litre borosilicate glass kettle that lights up blue as it boils. Beyond looking good on the counter, glass means you can actually see limescale building up and clean it before it taints the tea.',
    highlights: [
      '2.2L borosilicate glass body',
      'Blue LED illumination while boiling',
      'See limescale before it spoils your tea',
      '360° cordless base',
      'Auto shut-off and boil-dry protection',
    ],
    specs: [
      { label: 'Capacity', value: '2.2 L' },
      { label: 'Model', value: 'HM-2515' },
      { label: 'Body', value: 'Borosilicate glass' },
      { label: 'Power', value: '1800 W' },
      { label: 'Lighting', value: 'Blue LED' },
      { label: 'Warranty', value: '12 months' },
    ],
    reviews: [
      rv('Aisha Namuli', 'Kira', 5, 'Looks smart on the counter',
        'The blue light is a gimmick but I love it. More useful is seeing when it needs descaling.', '2026-08-07'),
      rv('Doreen Kabuye', 'Mukono', 4, 'Handle with care',
        'It is glass, so mind the knocks. Boils fast and looks lovely.', '2026-07-17'),
    ],
  },
  {
    id: 'p31',
    slug: 'adh-18l-stainless-electric-kettle',
    name: 'ADH 1.8L Stainless Steel Kettle',
    tagline: 'Gold-brown finish, automatic shut-off.',
    brand: 'ADH',
    category: 'Small Appliances',
    price: 31000,
    image: asset('/products/goldkettle.webp'),
    gallery: STD,
    badges: ['Express'],
    rating: 4.0, reviewCount: 276, stock: 74,
    warrantyMonths: 12, powerWatts: 1500, capacity: '1.8 L', colour: 'Gold Brown',
    express: true,
    description:
      'A 1.8 litre stainless kettle in a warm gold-brown finish, with automatic shut-off at boil and dry-boil protection. The sensible everyday kettle at an everyday price.',
    highlights: [
      '1.8L stainless steel body',
      'Automatic shut-off at boil',
      'Dry-boil protection',
      'Cordless 360° base',
      'Concealed element for easy cleaning',
    ],
    specs: [
      { label: 'Capacity', value: '1.8 L' },
      { label: 'Power', value: '1500 W' },
      { label: 'Body', value: 'Stainless steel' },
      { label: 'Safety', value: 'Auto shut-off + dry-boil cut-out' },
      { label: 'Finish', value: 'Gold brown' },
      { label: 'Warranty', value: '12 months' },
    ],
    reviews: [
      rv('Nabukeera Faith', 'Kawempe', 4, 'Nice colour, works well',
        'Matches my kitchen and boils quickly. For thirty thousand it is hard to complain.', '2026-08-03'),
      rv('Sylvia Kemigisha', 'Bushenyi', 4, 'Reliable',
        'Six months of daily use, no problems.', '2026-06-28'),
    ],
  },
  {
    id: 'p32',
    slug: 'pixel-25l-double-layer-kettle',
    name: 'Pixel 2.5L Anti-Scald Electric Kettle',
    tagline: 'Double-walled in vintage green.',
    brand: 'Pixel',
    category: 'Small Appliances',
    price: 23000,
    image: asset('/products/greenkettle.webp'),
    gallery: STD,
    badges: ['Express'],
    rating: 4.1, reviewCount: 189, stock: 81,
    warrantyMonths: 12, powerWatts: 1500, capacity: '2.5 L', colour: 'Vintage Green',
    express: true,
    description:
      'A 2.5 litre double-layer kettle: the inner wall is stainless steel, the outer stays cool to touch. The largest capacity in our kettle range, and the safest around small children.',
    highlights: [
      '2.5L — the largest capacity kettle we stock',
      'Double-layer anti-scald body, cool to touch',
      'Automatic power off at boil',
      'Stainless steel interior',
      'Distinctive vintage green finish',
    ],
    specs: [
      { label: 'Capacity', value: '2.5 L' },
      { label: 'Power', value: '1500 W' },
      { label: 'Construction', value: 'Double layer, anti-scald' },
      { label: 'Interior', value: 'Stainless steel' },
      { label: 'Safety', value: 'Automatic power off' },
      { label: 'Warranty', value: '12 months' },
    ],
    reviews: [
      rv('Esther Nagawa', 'Kawuku', 4, 'Cool outside, safe for kids',
        'My children run through the kitchen constantly. The outside never gets hot.', '2026-07-29'),
      rv('Catherine Nabbosa', 'Kyanja', 4, 'Big and cheap',
        'Two and a half litres for this price is good value. Colour is lovely.', '2026-06-22'),
    ],
  },
  {
    id: 'p33',
    slug: 'hoffmans-08l-travel-kettle',
    name: 'Hoffmans 0.8L Compact Travel Kettle',
    tagline: 'Fits in a bag, boils in a hostel room.',
    brand: 'Hoffmans',
    category: 'Small Appliances',
    price: 31000,
    image: asset('/products/travelkettle.webp'),
    gallery: STD,
    badges: ['Express'],
    rating: 4.0, reviewCount: 91, stock: 63,
    warrantyMonths: 12, powerWatts: 800, capacity: '0.8 L', colour: 'Black & Bronze',
    express: true,
    description:
      'A 0.8 litre double-wall travel kettle that packs into a bag — for hostel rooms, hotel stays and long-distance travel. Low 800W draw so it works on weak supply.',
    highlights: [
      'Compact 0.8L — packs into a travel bag',
      'Double-wall stainless steel, cool to touch',
      'Low 800W draw works on weak supply',
      'Auto shut-off',
      'Ideal for students and travellers',
    ],
    specs: [
      { label: 'Capacity', value: '0.8 L' },
      { label: 'Model', value: 'HM-2563' },
      { label: 'Power', value: '800 W' },
      { label: 'Construction', value: 'Double-wall stainless' },
      { label: 'Use', value: 'Travel, hostel, office' },
      { label: 'Warranty', value: '12 months' },
    ],
    reviews: [
      rv('Samuel Tugume', 'Kabale', 4, 'Perfect for the hostel',
        'Small enough to hide in my locker and boils enough for two cups.', '2026-08-10'),
    ],
  },
  {
    id: 'p34',
    slug: 'adh-2l-fast-boiling-percolator',
    name: 'ADH 2L Fast-Boiling Percolator',
    tagline: 'The office tea urn, at duka prices.',
    brand: 'ADH',
    category: 'Small Appliances',
    price: 20000,
    image: asset('/products/percolator.webp'),
    gallery: STD,
    badges: ['Express'],
    rating: 4.0, reviewCount: 318, stock: 92,
    warrantyMonths: 12, powerWatts: 1000, capacity: '2 L', colour: 'Silver & Black',
    express: true,
    description:
      'Two litres with a front tap — fill once and draw hot water all morning. Functionally identical to the Roch percolator and priced within a thousand shillings of it; pick on availability.',
    highlights: [
      '2L capacity with front spigot tap',
      'Keeps water hot for serving',
      'Stainless steel body',
      'Auto cut-out and boil-dry protection',
      'Offices, guest houses and events',
    ],
    specs: [
      { label: 'Capacity', value: '2 L' },
      { label: 'Power', value: '1000 W' },
      { label: 'Dispensing', value: 'Front tap' },
      { label: 'Body', value: 'Stainless steel' },
      { label: 'Safety', value: 'Auto cut-out' },
      { label: 'Warranty', value: '12 months' },
    ],
    reviews: [
      rv('Julius Wanyama', 'Mbale', 4, 'Same as the Roch',
        'Bought one of each for two offices. Honestly cannot tell them apart in use.', '2026-07-24'),
    ],
  },
  {
    id: 'p35',
    slug: 'scarlet-2l-electric-percolator',
    name: 'Scarlet 2L Electric Percolator',
    tagline: 'Simple, cheap, does one job well.',
    brand: 'Scarlet',
    category: 'Small Appliances',
    price: 21000,
    image: asset('/products/percolator.webp'),
    gallery: STD,
    badges: [],
    rating: 3.9, reviewCount: 204, stock: 70,
    warrantyMonths: 12, powerWatts: 1000, capacity: '2 L', colour: 'Silver & Black',
    description:
      'A no-frills 2 litre percolator with a serving tap. Nothing clever, nothing to break — the kind of appliance that quietly works for years in a staff kitchen.',
    highlights: [
      '2L with serving tap',
      'Straightforward, durable construction',
      'Stainless steel body',
      'Automatic cut-out',
      'Common spares, easy to service locally',
    ],
    specs: [
      { label: 'Capacity', value: '2 L' },
      { label: 'Power', value: '1000 W' },
      { label: 'Dispensing', value: 'Front tap' },
      { label: 'Body', value: 'Stainless steel' },
      { label: 'Safety', value: 'Auto cut-out' },
      { label: 'Warranty', value: '12 months' },
    ],
    reviews: [
      rv('Tom Byaruhanga', 'Fort Portal', 4, 'Been running two years',
        'Ours has been on every working day for two years. Still fine.', '2026-06-15'),
    ],
  },
  {
    id: 'p36',
    slug: 'hoffmans-dry-flat-iron-1200w',
    name: 'Hoffmans 1200W Dry Flat Iron',
    tagline: 'No steam, no water, no drips.',
    brand: 'Hoffmans',
    category: 'Small Appliances',
    price: 32000,
    image: asset('/products/dryiron.webp'),
    gallery: STD,
    badges: ['Express'],
    rating: 4.1, reviewCount: 232, stock: 68,
    warrantyMonths: 12, powerWatts: 1200, capacity: '—', colour: 'Silver & Black',
    express: true,
    description:
      'A plain dry iron with a temperature dial and a non-stick soleplate. No tank to fill, nothing to drip onto a white shirt, and no limescale to descale — which is why plenty of people still prefer them.',
    highlights: [
      '1200W with non-stick soleplate',
      'No water tank — nothing to drip or leak',
      'No limescale, so nothing to descale',
      'Adjustable fabric temperature dial',
      'Light and quick to heat',
    ],
    specs: [
      { label: 'Power', value: '1200 W' },
      { label: 'Model', value: 'HM-9035' },
      { label: 'Type', value: 'Dry iron (no steam)' },
      { label: 'Soleplate', value: 'Non-stick' },
      { label: 'Control', value: 'Fabric temperature dial' },
      { label: 'Warranty', value: '12 months' },
    ],
    reviews: [
      rv('Lydia Akello', 'Tororo', 4, 'No more water stains',
        'My steam iron kept spitting rusty water on white shirts. This cannot, because there is no water.', '2026-08-02'),
      rv('Peter Odhiambo', 'Nakawa', 4, 'Cheap and quick',
        'Heats in seconds. For uniforms and shirts it is all I need.', '2026-07-08'),
    ],
  },
  {
    id: 'p37',
    slug: 'couronne-2in1-steel-blender-15l',
    name: 'Couronne 1.5L 2-in-1 Steel Blender',
    tagline: 'Stainless collar, high-speed motor.',
    brand: 'Couronne',
    category: 'Kitchen',
    price: 65000,
    image: asset('/products/steelblender.webp'),
    gallery: STD,
    badges: [],
    rating: 4.2, reviewCount: 156, stock: 37,
    warrantyMonths: 12, powerWatts: 500, capacity: '1.5 L', colour: 'Silver',
    description:
      'A 1.5 litre high-speed blender with a stainless steel collar and a second mill jar for dry grinding. A step up in build quality from the plastic-bodied budget machines.',
    highlights: [
      '1.5L jug plus a dry grinding jar',
      'Stainless steel collar and blade assembly',
      'High-speed motor with pulse',
      'Grinds groundnuts, simsim and spices',
      'Dishwasher-safe jars',
    ],
    specs: [
      { label: 'Power', value: '500 W' },
      { label: 'Jug capacity', value: '1.5 L' },
      { label: 'Attachments', value: 'Blending jug + dry mill' },
      { label: 'Build', value: 'Stainless steel collar' },
      { label: 'Speeds', value: '2 + pulse' },
      { label: 'Warranty', value: '12 months' },
    ],
    reviews: [
      rv('Zainab Nakintu', 'Nsambya', 4, 'Feels solid',
        'The metal parts make it feel like it will last, unlike the all-plastic ones.', '2026-07-31'),
    ],
  },
  {
    id: 'p38',
    slug: 'couronne-15l-blender-grinder-tyb313',
    name: 'Couronne 1.5L Blender with Grinding Mill',
    tagline: 'Two jars, one motor, in blue.',
    brand: 'Couronne',
    category: 'Kitchen',
    price: 55000,
    image: asset('/products/jarblender.webp'),
    gallery: STD,
    badges: ['Express'],
    rating: 4.0, reviewCount: 118, stock: 44,
    warrantyMonths: 12, powerWatts: 450, capacity: '1.5 L', colour: 'Blue',
    express: true,
    description:
      'The TYB 313: a 1.5 litre blending jug plus a dedicated grinding mill, so wet and dry never share a jar. Straightforward and easy to strip down for washing.',
    highlights: [
      '1.5L blending jug plus separate grinder',
      'Wet and dry stay in separate jars',
      'Stainless steel blades',
      'Two speeds plus pulse',
      'Easy to dismantle and wash',
    ],
    specs: [
      { label: 'Power', value: '450 W' },
      { label: 'Model', value: 'TYB 313' },
      { label: 'Jug capacity', value: '1.5 L' },
      { label: 'Attachments', value: 'Blending jug + grinding mill' },
      { label: 'Speeds', value: '2 + pulse' },
      { label: 'Warranty', value: '12 months' },
    ],
    reviews: [
      rv('Miriam Achieng', 'Jinja', 4, 'Separate jars is the point',
        'I hated washing groundnut oil out of the smoothie jug. Two jars solves it.', '2026-08-13'),
    ],
  },
  {
    id: 'p39',
    slug: 'adh-2in1-unbreakable-jar-blender',
    name: 'ADH 2-in-1 Unbreakable Jar Blender',
    tagline: 'Drop it. It will be fine.',
    brand: 'ADH',
    category: 'Kitchen',
    price: 59000,
    image: asset('/products/jarblender.webp'),
    gallery: STD,
    badges: ['Express'],
    rating: 4.1, reviewCount: 187, stock: 41,
    warrantyMonths: 12, powerWatts: 400, capacity: '1.5 L', colour: 'White & Green',
    express: true,
    description:
      'The ACB 737C uses a shatterproof polycarbonate jar instead of glass — a sensible choice in a busy kitchen or where children help with the cooking. Includes a grinding attachment.',
    highlights: [
      'Unbreakable polycarbonate jar, not glass',
      'Safe in a busy household kitchen',
      'Grinding mill attachment included',
      'Stainless steel blades',
      '1-year warranty',
    ],
    specs: [
      { label: 'Power', value: '400 W' },
      { label: 'Model', value: 'ACB 737C (25D)' },
      { label: 'Jar', value: 'Unbreakable polycarbonate' },
      { label: 'Capacity', value: '1.5 L' },
      { label: 'Attachments', value: 'Grinding mill' },
      { label: 'Warranty', value: '12 months' },
    ],
    reviews: [
      rv('Winnie Amongin', 'Soroti', 4, 'Survived being knocked off the counter',
        'It fell off the counter in the first week and bounced. A glass jug would have been finished.', '2026-07-27'),
      rv('Denis Ssebugwawo', 'Masaka', 4, 'Good for a busy kitchen',
        'With house help and children in and out, unbreakable was the right call.', '2026-06-18'),
    ],
  },
]

export const getProduct = (slug: string) => products.find((p) => p.slug === slug)

export const priceBounds = products.reduce(
  (acc, p) => ({ min: Math.min(acc.min, p.price), max: Math.max(acc.max, p.price) }),
  { min: Infinity, max: 0 },
)

export const brands = [...new Set(products.map((p) => p.brand))].sort()

export const collections = [
  {
    slug: 'kitchen',
    title: 'The Kitchen',
    blurb: 'Cookers, microwaves, blenders and air fryers.',
    image: asset('/products/cooker.webp'),
    category: 'Kitchen' as const,
  },
  {
    slug: 'cooling',
    title: 'Cold Storage',
    blurb: 'Fridges and freezers built for Ugandan power.',
    image: asset('/products/fridge-dispenser.webp'),
    category: 'Cooling' as const,
  },
  {
    slug: 'entertainment',
    title: 'The Living Room',
    blurb: 'Smart TVs from 32" to 50", free-to-air ready.',
    image: asset('/products/tv.webp'),
    category: 'Home Entertainment' as const,
  },
  {
    slug: 'laundry',
    title: 'Laundry Day',
    blurb: 'Twin tubs and automatics that spin near dry.',
    image: asset('/products/frontload.webp'),
    category: 'Laundry' as const,
  },
]
