import dotenv from "dotenv";
import connectDB from "./config/db.js";
import User from "./models/User.js";
import Category from "./models/Category.js";
import Product from "./models/Product.js";

dotenv.config();
await connectDB();

/**
 * Chikwafu catalogue — 78 products across 7 categories, priced in UGX.
 * Sourced from live Jumia Uganda listings plus the Chikwafu margin.
 *
 * Images are served by the storefront from /jumia/*.webp. Set
 * ASSET_BASE if the front end is hosted somewhere else.
 */
const ASSET_BASE = process.env.ASSET_BASE || "";

const run = async () => {
  await Promise.all([User.deleteMany(), Category.deleteMany(), Product.deleteMany()]);

  await User.create({
    name: "Chikwafu Admin",
    email: "admin@chikwafu.com",
    password: "admin123",
    role: "admin",
  });

  const categoryData = [
    { name: "Kitchen", itemCount: 30, featured: true },
    { name: "Laundry", itemCount: 4, featured: true },
    { name: "Cooling", itemCount: 8, featured: true },
    { name: "Home Entertainment", itemCount: 16, featured: true },
    { name: "Small Appliances", itemCount: 11, featured: true },
    { name: "Phones & Tablets", itemCount: 4, featured: true },
    { name: "Computing", itemCount: 5, featured: true },
  ];
  const categories = [];
  for (const c of categoryData) categories.push(await Category.create(c));
  const byName = (n) => categories.find((c) => c.name === n)._id;

  const products = [
    {
      name: "Hisense 270L Double-Door Fridge with Water Dispenser",
      brand: "Hisense",
      category: byName("Cooling"),
      price: 1045000,
      stock: 9,
      sku: "HISENSE-270L-DOUBLE-DOOR",
      images: [ASSET_BASE + "/jumia/fridge-hisense270.webp"],
      description: "A 270 litre double-door fridge with an external water dispenser, so a cold glass costs you nothing in cooling. Defrost operation, toughened glass shelves and a vegetable crisper. Backed by a three-year Hisense warranty honoured locally.",
      tags: ["Cooling", "Hisense", "Free installation"],
      isFeatured: true,
      rating: 4.5,
      numReviews: 214,
    },
    {
      name: "Hisense 160L Double-Door Refrigerator",
      brand: "Hisense",
      category: byName("Cooling"),
      price: 768000,
      stock: 17,
      sku: "HISENSE-160L-DOUBLE-DOOR",
      images: [ASSET_BASE + "/jumia/fridge-hisense160.webp"],
      description: "A 160 litre double-door fridge that fits a small kitchen without giving up a separate freezer compartment. Defrost operation keeps running costs low and the reversible door suits either corner.",
      tags: ["Cooling", "Hisense", "Bestseller"],
      isFeatured: true,
      rating: 4.4,
      numReviews: 486,
    },
    {
      name: "ADH 276L Double-Door Refrigerator",
      brand: "ADH",
      category: byName("Cooling"),
      price: 850000,
      stock: 12,
      sku: "ADH-276L-DOUBLE-DOOR-REF",
      images: [ASSET_BASE + "/jumia/clean-fridge-double.webp"],
      description: "At 276 litres this handles a full weekly shop for a large household, with a generous freezer above and adjustable shelving below. Three-year warranty on the sealed system.",
      tags: ["Cooling", "ADH"],
      rating: 4.2,
      numReviews: 158,
    },
    {
      name: "Pixel 120L Single-Door Refrigerator",
      brand: "Pixel",
      category: byName("Cooling"),
      price: 373000,
      stock: 34,
      sku: "PIXEL-120L-SINGLE-DOOR-R",
      images: [ASSET_BASE + "/jumia/fridge-pixel120.webp"],
      description: "A 120 litre single-door fridge with a small internal freezer box — the standard choice for a hostel room, small flat or an office kitchen. Low power draw and quiet enough to sit in a bedroom.",
      tags: ["Cooling", "Pixel", "Bestseller"],
      rating: 3.8,
      numReviews: 941,
    },
    {
      name: "ADH 200L Chest Freezer",
      brand: "ADH",
      category: byName("Cooling"),
      price: 807000,
      stock: 10,
      sku: "ADH-200L-CHEST-FREEZER",
      images: [ASSET_BASE + "/jumia/clean-freezer.webp"],
      description: "A 200 litre chest freezer with a sliding lid — the workhorse behind every duka selling cold drinks and every household that buys meat in bulk. Holds temperature for hours during an outage thanks to thick insulation.",
      tags: ["Cooling", "ADH", "Free installation"],
      rating: 4.3,
      numReviews: 176,
    },
    {
      name: "Blueflame 50×50cm 3 Gas + 1 Electric Cooker",
      brand: "Blueflame",
      category: byName("Kitchen"),
      price: 646000,
      stock: 11,
      sku: "BLUEFLAME-50X50-3-GAS-1-",
      images: [ASSET_BASE + "/jumia/clean-cooker-4burner.webp"],
      description: "Made in Turkey, this 50×50cm cooker gives you three gas burners plus one electric hotplate, so you can still cook when the gas runs out mid-meal. The electric oven below holds temperature well enough for baking.",
      tags: ["Kitchen", "Blueflame", "Free installation"],
      isFeatured: true,
      rating: 4.5,
      numReviews: 263,
    },
    {
      name: "SPJ 50×50cm 3 Gas + 1 Hotplate Cooker",
      brand: "SPJ",
      category: byName("Kitchen"),
      price: 402000,
      stock: 19,
      sku: "SPJ-50X50-3-GAS-1-ELECTR",
      images: [ASSET_BASE + "/jumia/cooker-spj3gas.webp"],
      description: "The entry point into a proper standing cooker: three gas burners, an electric hotplate and a gas oven, in a 50×50cm footprint that fits most Kampala kitchens. Three-year warranty is unusual at this price.",
      tags: ["Kitchen", "SPJ"],
      rating: 4.1,
      numReviews: 342,
    },
    {
      name: "Hisense 20L Manual Microwave",
      brand: "Hisense",
      category: byName("Kitchen"),
      price: 230000,
      stock: 26,
      sku: "HISENSE-20L-MANUAL-MICRO",
      images: [ASSET_BASE + "/jumia/micro-hisense20.webp"],
      description: "A 20 litre microwave with two mechanical dials — power and timer. Nothing to learn, nothing to break, and no touch panel to stop responding. Ideal for reheating and defrosting.",
      tags: ["Kitchen", "Hisense", "express"],
      rating: 4.3,
      numReviews: 197,
    },
    {
      name: "Hoffmans 6L Touch Screen Air Fryer",
      brand: "Hoffmans",
      category: byName("Kitchen"),
      price: 121000,
      stock: 41,
      sku: "HOFFMANS-6L-TOUCH-AIR-FR",
      images: [ASSET_BASE + "/jumia/fryer-hoffmans6018.webp"],
      description: "A 6 litre oil-free air fryer with a touch screen and preset programmes. Rapid hot-air circulation crisps chips, chicken and samosas using a fraction of the oil — and a fraction of the power an oven would draw.",
      tags: ["Kitchen", "Hoffmans", "express", "New"],
      isFeatured: true,
      isNewArrival: true,
      rating: 4.4,
      numReviews: 231,
    },
    {
      name: "Panda 350W 1.75L 2-in-1 Juice Blender",
      brand: "Panda",
      category: byName("Kitchen"),
      price: 53000,
      stock: 52,
      sku: "PANDA-350W-2IN1-JUICE-BL",
      images: [ASSET_BASE + "/jumia/blend-panda350.webp"],
      description: "A 350W blender with a 1.75 litre jug plus a dry mill attachment, so it handles smoothies and grinding in the same machine. Straightforward, affordable and easy to strip down for washing.",
      tags: ["Kitchen", "Panda", "express"],
      rating: 4,
      numReviews: 287,
    },
    {
      name: "Nyota 1800W Glass Jug Blender",
      brand: "Nyota",
      category: byName("Kitchen"),
      price: 289000,
      compareAtPrice: 349000,
      stock: 23,
      sku: "NYOTA-1800W-GLASS-JUG-BL",
      images: [ASSET_BASE + "/products/blender.webp"],
      description: "When a 350W machine is not enough: an 1800W copper-wound motor with a six-point blade and a thermal-shock resistant glass jug. Turns dry groundnuts into fine paste and ice into snow.",
      tags: ["Kitchen", "Nyota", "express", "Bestseller"],
      isFeatured: true,
      rating: 4.7,
      numReviews: 214,
    },
    {
      name: "Kabira 1.8L Digital Rice Cooker & Steamer",
      brand: "Kabira",
      category: byName("Kitchen"),
      price: 189000,
      compareAtPrice: 235000,
      stock: 38,
      sku: "KABIRA-18L-DIGITAL-RICE-",
      images: [ASSET_BASE + "/products/ricecooker.webp"],
      description: "Ten cups of cooked rice with every grain separate, plus a stacking steamer basket for matooke, cassava or vegetables above. Automatic keep-warm holds supper for up to twelve hours.",
      tags: ["Kitchen", "Kabira", "express"],
      rating: 4.6,
      numReviews: 121,
    },
    {
      name: "Roch 2L Fast-Boiling Percolator Kettle",
      brand: "Roch",
      category: byName("Small Appliances"),
      price: 19000,
      stock: 88,
      sku: "ROCH-2L-FAST-BOILING-PER",
      images: [ASSET_BASE + "/jumia/perc-roch2l.webp"],
      description: "A 2 litre percolator with a spigot tap — fill it once in the morning and draw hot water for tea all day. The standard fixture in Ugandan offices and guest houses, and hard to beat at this price.",
      tags: ["Small Appliances", "Roch", "express", "Bestseller"],
      rating: 4.1,
      numReviews: 624,
    },
    {
      name: "Ssese 1.7L Cordless Kettle",
      brand: "Ssese",
      category: byName("Small Appliances"),
      price: 129000,
      compareAtPrice: 165000,
      stock: 61,
      sku: "SSESE-17L-CORDLESS-KETTL",
      images: [ASSET_BASE + "/products/kettle.webp"],
      description: "Double-walled brushed stainless steel so the outside stays cool to touch. A concealed 2200W element boils 1.7 litres in about three minutes and shuts off automatically at boil, or if switched on dry.",
      tags: ["Small Appliances", "Ssese", "express"],
      isFeatured: true,
      rating: 4.8,
      numReviews: 402,
    },
    {
      name: "Ssese Ceramic Soleplate Steam Iron",
      brand: "Ssese",
      category: byName("Small Appliances"),
      price: 98000,
      compareAtPrice: 125000,
      stock: 67,
      sku: "SSESE-CERAMIC-STEAM-IRON",
      images: [ASSET_BASE + "/products/iron.webp"],
      description: "A 2400W iron with a scratch-resistant ceramic soleplate that slides over cotton and kitenge without catching. Anti-drip means no water marks on a white shirt, and self-clean handles hard water.",
      tags: ["Small Appliances", "Ssese", "express"],
      rating: 4.4,
      numReviews: 189,
    },
    {
      name: "Hisense 9kg Automatic Front-Load Washing Machine",
      brand: "Hisense",
      category: byName("Laundry"),
      price: 1375000,
      stock: 8,
      sku: "HISENSE-9KG-FRONT-LOAD-W",
      images: [ASSET_BASE + "/jumia/wash-hisense9kg.webp"],
      description: "A 9kg fully automatic front loader — load it, choose a programme and walk away. The high-speed spin leaves washing nearly dry, which matters in the rainy season when line-drying is a gamble.",
      tags: ["Laundry", "Hisense", "Free installation"],
      isFeatured: true,
      rating: 4.5,
      numReviews: 168,
    },
    {
      name: "SPJ 10kg Twin Tub Washing Machine",
      brand: "SPJ",
      category: byName("Laundry"),
      price: 635000,
      stock: 21,
      sku: "SPJ-10KG-TWIN-TUB-WASHIN",
      images: [ASSET_BASE + "/jumia/clean-twintub-white.webp"],
      description: "The twin tub remains the practical choice where water supply is unreliable: you fill it yourself, wash a big 10kg load, then move it to the spinner. Far less water and power than an automatic, and a five-year warranty.",
      tags: ["Laundry", "SPJ", "Bestseller"],
      rating: 4.2,
      numReviews: 304,
    },
    {
      name: "Pixel 8kg Twin Tub Washing Machine",
      brand: "Pixel",
      category: byName("Laundry"),
      price: 549000,
      stock: 24,
      sku: "PIXEL-8KG-TWIN-TUB-WASHI",
      images: [ASSET_BASE + "/jumia/clean-twintub-grey.webp"],
      description: "An 8kg twin tub for households making the jump from hand washing. Manual fill, separate spinner, and light enough for one person to move out to the yard and back.",
      tags: ["Laundry", "Pixel"],
      rating: 4,
      numReviews: 213,
    },
    {
      name: "Hisense 50\" 4K Smart TV (50A4Q)",
      brand: "Hisense",
      category: byName("Home Entertainment"),
      price: 1066000,
      stock: 13,
      sku: "HISENSE-50-INCH-SMART-TV",
      images: [ASSET_BASE + "/jumia/clean-tv50.webp"],
      description: "A 50 inch smart panel running Netflix, YouTube and Showmax over built-in WiFi, with a free-to-air tuner so local channels work without an extra decoder. Three-year Hisense warranty honoured in Kampala.",
      tags: ["Home Entertainment", "Hisense", "Bestseller"],
      isFeatured: true,
      rating: 4.6,
      numReviews: 341,
    },
    {
      name: "TCL 43\" Bezel-Less HD Smart Google TV",
      brand: "TCL",
      category: byName("Home Entertainment"),
      price: 836000,
      stock: 16,
      sku: "TCL-43-INCH-GOOGLE-TV-S3",
      images: [ASSET_BASE + "/jumia/tv-tcl32s5k.webp"],
      description: "A 43 inch bezel-less panel running full Google TV, so the remote has a microphone and every app you would expect is on the store. The right size for a sitting room without dominating it.",
      tags: ["Home Entertainment", "TCL"],
      rating: 4.4,
      numReviews: 126,
    },
    {
      name: "Skyworth 43\" QLED Google TV",
      brand: "Skyworth",
      category: byName("Home Entertainment"),
      price: 782000,
      stock: 14,
      sku: "SKYWORTH-43-INCH-QLED-GO",
      images: [ASSET_BASE + "/jumia/clean-tv43-b.webp"],
      description: "A QLED panel at 43 inches, which means richer, more saturated colour than a standard LED — noticeable on football pitches and nature programmes. Runs Google TV, with a three-year warranty.",
      tags: ["Home Entertainment", "Skyworth", "New"],
      isNewArrival: true,
      rating: 4.3,
      numReviews: 87,
    },
    {
      name: "Itel 43\" HD Android Smart TV",
      brand: "Itel",
      category: byName("Home Entertainment"),
      price: 549000,
      stock: 27,
      sku: "ITEL-43-INCH-HD-SMART-TV",
      images: [ASSET_BASE + "/jumia/clean-tv43-a.webp"],
      description: "A 43 inch Android smart TV with Netflix and YouTube built in, aimed squarely at households who want a big smart screen without spending a million shillings. Two-year warranty.",
      tags: ["Home Entertainment", "Itel"],
      rating: 4.1,
      numReviews: 194,
    },
    {
      name: "Hisense 32\" HDR LED Free-to-Air TV",
      brand: "Hisense",
      category: byName("Home Entertainment"),
      price: 351000,
      stock: 45,
      sku: "HISENSE-32-INCH-HDR-LED-",
      images: [ASSET_BASE + "/jumia/tv-hisense32.webp"],
      description: "A 32 inch HDR LED with a built-in free-to-air tuner — the default second TV for a bedroom, shop counter or salon. Three-year Hisense warranty and low enough power draw to run off a modest inverter.",
      tags: ["Home Entertainment", "Hisense", "Bestseller"],
      rating: 3.8,
      numReviews: 1264,
    },
    {
      name: "Mitech 40\" Full HD LED TV with Decoder",
      brand: "Mitech",
      category: byName("Home Entertainment"),
      price: 453000,
      stock: 22,
      sku: "MITECH-40-INCH-FULL-HD-T",
      images: [ASSET_BASE + "/jumia/clean-tv40.webp"],
      description: "A 40 inch Full HD panel with the decoder built in, so free-to-air channels need nothing more than an aerial. A sensible middle size between a 32 and a 43.",
      tags: ["Home Entertainment", "Mitech"],
      rating: 4,
      numReviews: 148,
    },
    {
      name: "Hoffmans 14-in-1 6L Digital Pressure Cooker",
      brand: "Hoffmans",
      category: byName("Kitchen"),
      price: 199000,
      stock: 29,
      sku: "HOFFMANS-14IN1-ELECTRIC-",
      images: [ASSET_BASE + "/jumia/pcook-hoffmans718.webp"],
      description: "Fourteen programmes in a single 6 litre pot: pressure cook beans in twenty minutes instead of two hours, steam matooke, slow cook, or drop in the basket and air fry. The obvious choice when kitchen space and gas money are both tight.",
      tags: ["Kitchen", "Hoffmans", "express", "Express"],
      isFeatured: true,
      rating: 4.4,
      numReviews: 168,
    },
    {
      name: "ADH 25-in-1 6L Multipurpose Pressure Cooker",
      brand: "ADH",
      category: byName("Kitchen"),
      price: 151000,
      stock: 33,
      sku: "ADH-25IN1-ELECTRIC-PRESS",
      images: [ASSET_BASE + "/jumia/pcook-adh25in1.webp"],
      description: "A 6 litre multipurpose cooker with twenty-five preset programmes covering rice, beans, meat, porridge, cake and yoghurt. Sealed pressure cooking cuts both time and gas consumption dramatically.",
      tags: ["Kitchen", "ADH", "express", "Express"],
      rating: 4.2,
      numReviews: 97,
    },
    {
      name: "Pixel 7L Multi-Function Pressure Cooker",
      brand: "Pixel",
      category: byName("Kitchen"),
      price: 185000,
      stock: 21,
      sku: "PIXEL-7L-ELECTRIC-PRESSU",
      images: [ASSET_BASE + "/jumia/pcook-pixel7l.webp"],
      description: "At seven litres this is the largest of our pressure cookers, sized for big households or anyone who batch-cooks at the weekend. Includes a steamer insert for cooking two things at once.",
      tags: ["Kitchen", "Pixel"],
      rating: 4.1,
      numReviews: 74,
    },
    {
      name: "Sonashi 25L Digital Microwave with Grill",
      brand: "Sonashi",
      category: byName("Kitchen"),
      price: 426000,
      stock: 12,
      sku: "SONASHI-25L-DIGITAL-MICR",
      images: [ASSET_BASE + "/jumia/micro-sonashi25.webp"],
      description: "A 25 litre digital microwave with a 1000W grill element for browning, five power levels and a child safety lock. The pull-open door handle is easier than a push-button latch when your hands are full.",
      tags: ["Kitchen", "Sonashi"],
      rating: 4.3,
      numReviews: 58,
    },
    {
      name: "Pixel 6L Oil-Free Air Fryer",
      brand: "Pixel",
      category: byName("Kitchen"),
      price: 107000,
      stock: 46,
      sku: "PIXEL-6L-OIL-FREE-AIR-FR",
      images: [ASSET_BASE + "/jumia/fryer-pixel6l.webp"],
      description: "A straightforward 6 litre air fryer with a temperature dial and timer rather than a touch screen — fewer things to fail, and cheaper for it. Same rapid hot-air crisping.",
      tags: ["Kitchen", "Pixel", "express", "Express"],
      rating: 4.2,
      numReviews: 212,
    },
    {
      name: "Hoffmans 2.2L Glass Kettle with LED",
      brand: "Hoffmans",
      category: byName("Small Appliances"),
      price: 44000,
      stock: 58,
      sku: "HOFFMANS-22L-GLASS-LED-K",
      images: [ASSET_BASE + "/jumia/kettle-hoffmans2515.webp"],
      description: "A 2.2 litre borosilicate glass kettle that lights up blue as it boils. Beyond looking good on the counter, glass means you can actually see limescale building up and clean it before it taints the tea.",
      tags: ["Small Appliances", "Hoffmans", "express", "Express"],
      isFeatured: true,
      rating: 4.3,
      numReviews: 143,
    },
    {
      name: "ADH 1.8L Stainless Steel Kettle",
      brand: "ADH",
      category: byName("Small Appliances"),
      price: 31000,
      stock: 74,
      sku: "ADH-18L-STAINLESS-ELECTR",
      images: [ASSET_BASE + "/jumia/kettle-adh18.webp"],
      description: "A 1.8 litre stainless kettle in a warm gold-brown finish, with automatic shut-off at boil and dry-boil protection. The sensible everyday kettle at an everyday price.",
      tags: ["Small Appliances", "ADH", "express", "Express"],
      rating: 4,
      numReviews: 276,
    },
    {
      name: "Pixel 2.5L Anti-Scald Electric Kettle",
      brand: "Pixel",
      category: byName("Small Appliances"),
      price: 23000,
      stock: 81,
      sku: "PIXEL-25L-DOUBLE-LAYER-K",
      images: [ASSET_BASE + "/jumia/kettle-pixel25.webp"],
      description: "A 2.5 litre double-layer kettle: the inner wall is stainless steel, the outer stays cool to touch. The largest capacity in our kettle range, and the safest around small children.",
      tags: ["Small Appliances", "Pixel", "express", "Express"],
      rating: 4.1,
      numReviews: 189,
    },
    {
      name: "Hoffmans 0.8L Compact Travel Kettle",
      brand: "Hoffmans",
      category: byName("Small Appliances"),
      price: 31000,
      stock: 63,
      sku: "HOFFMANS-08L-TRAVEL-KETT",
      images: [ASSET_BASE + "/jumia/kettle-hoffmans2513.webp"],
      description: "A 0.8 litre double-wall travel kettle that packs into a bag — for hostel rooms, hotel stays and long-distance travel. Low 800W draw so it works on weak supply.",
      tags: ["Small Appliances", "Hoffmans", "express", "Express"],
      rating: 4,
      numReviews: 91,
    },
    {
      name: "ADH 2L Fast-Boiling Percolator",
      brand: "ADH",
      category: byName("Small Appliances"),
      price: 20000,
      stock: 92,
      sku: "ADH-2L-FAST-BOILING-PERC",
      images: [ASSET_BASE + "/jumia/perc-adh2l.webp"],
      description: "Two litres with a front tap — fill once and draw hot water all morning. Functionally identical to the Roch percolator and priced within a thousand shillings of it; pick on availability.",
      tags: ["Small Appliances", "ADH", "express", "Express"],
      rating: 4,
      numReviews: 318,
    },
    {
      name: "Scarlet 2L Electric Percolator",
      brand: "Scarlet",
      category: byName("Small Appliances"),
      price: 21000,
      stock: 70,
      sku: "SCARLET-2L-ELECTRIC-PERC",
      images: [ASSET_BASE + "/jumia/perc-scarlet2l.webp"],
      description: "A no-frills 2 litre percolator with a serving tap. Nothing clever, nothing to break — the kind of appliance that quietly works for years in a staff kitchen.",
      tags: ["Small Appliances", "Scarlet"],
      rating: 3.9,
      numReviews: 204,
    },
    {
      name: "Hoffmans 1200W Dry Flat Iron",
      brand: "Hoffmans",
      category: byName("Small Appliances"),
      price: 32000,
      stock: 68,
      sku: "HOFFMANS-DRY-FLAT-IRON-1",
      images: [ASSET_BASE + "/jumia/iron-hoffmans9035.webp"],
      description: "A plain dry iron with a temperature dial and a non-stick soleplate. No tank to fill, nothing to drip onto a white shirt, and no limescale to descale — which is why plenty of people still prefer them.",
      tags: ["Small Appliances", "Hoffmans", "express", "Express"],
      rating: 4.1,
      numReviews: 232,
    },
    {
      name: "Couronne 1.5L 2-in-1 Steel Blender",
      brand: "Couronne",
      category: byName("Kitchen"),
      price: 65000,
      stock: 37,
      sku: "COURONNE-2IN1-STEEL-BLEN",
      images: [ASSET_BASE + "/jumia/blend-couronne2in1.webp"],
      description: "A 1.5 litre high-speed blender with a stainless steel collar and a second mill jar for dry grinding. A step up in build quality from the plastic-bodied budget machines.",
      tags: ["Kitchen", "Couronne"],
      rating: 4.2,
      numReviews: 156,
    },
    {
      name: "Couronne 1.5L Blender with Grinding Mill",
      brand: "Couronne",
      category: byName("Kitchen"),
      price: 55000,
      stock: 44,
      sku: "COURONNE-15L-BLENDER-GRI",
      images: [ASSET_BASE + "/jumia/blend-couronne313.webp"],
      description: "The TYB 313: a 1.5 litre blending jug plus a dedicated grinding mill, so wet and dry never share a jar. Straightforward and easy to strip down for washing.",
      tags: ["Kitchen", "Couronne", "express", "Express"],
      rating: 4,
      numReviews: 118,
    },
    {
      name: "ADH 2-in-1 Unbreakable Jar Blender",
      brand: "ADH",
      category: byName("Kitchen"),
      price: 59000,
      stock: 41,
      sku: "ADH-2IN1-UNBREAKABLE-JAR",
      images: [ASSET_BASE + "/jumia/blend-adh737c.webp"],
      description: "The ACB 737C uses a shatterproof polycarbonate jar instead of glass — a sensible choice in a busy kitchen or where children help with the cooking. Includes a grinding attachment.",
      tags: ["Kitchen", "ADH", "express", "Express"],
      rating: 4.1,
      numReviews: 187,
    },
    {
      name: "Roch 32\" HD Digital Satellite Free-to-Air TV",
      brand: "Roch",
      category: byName("Home Entertainment"),
      price: 307000,
      stock: 31,
      sku: "ROCH-32-INCH-FREE-TO-AIR",
      images: [ASSET_BASE + "/jumia/clean-tv32-b.webp"],
      description: "A 32 inch HD panel with a built-in satellite and free-to-air tuner. No smart apps — just channels, an HDMI port and a two-year warranty. The honest budget option for a bedroom or shop.",
      tags: ["Home Entertainment", "Roch"],
      rating: 3.4,
      numReviews: 57,
    },
    {
      name: "Roch 43\" Smart Android Frameless TV",
      brand: "Roch",
      category: byName("Home Entertainment"),
      price: 578000,
      stock: 18,
      sku: "ROCH-43-INCH-SMART-ANDRO",
      images: [ASSET_BASE + "/jumia/clean-tv43-a.webp"],
      description: "A frameless 43 inch Android smart TV with free-to-air built in. Netflix and YouTube run from the Play Store, and the thin bezel makes it look well above its price.",
      tags: ["Home Entertainment", "Roch"],
      rating: 4,
      numReviews: 112,
    },
    {
      name: "TCL 32\" QLED Smart TV with Decoder",
      brand: "TCL",
      category: byName("Home Entertainment"),
      price: 580000,
      stock: 15,
      sku: "TCL-32-INCH-QLED-SMART-T",
      images: [ASSET_BASE + "/jumia/tv-tcl32s5k.webp"],
      description: "The 32S5K brings QLED colour to a compact 32 inch panel, with 2K smart features and a built-in free-to-air decoder. Better colour than any standard LED at this size.",
      tags: ["Home Entertainment", "TCL"],
      rating: 4.3,
      numReviews: 64,
    },
    {
      name: "Globalstar 43\" QLED Frameless TV",
      brand: "Globalstar",
      category: byName("Home Entertainment"),
      price: 597000,
      stock: 20,
      sku: "GLOBALSTAR-43-INCH-QLED-",
      images: [ASSET_BASE + "/jumia/tv-globalstar43.webp"],
      description: "A 43 inch QLED frameless panel with satellite and free-to-air reception built in. Plug in an aerial and the local channels are there — nothing else to buy or subscribe to.",
      tags: ["Home Entertainment", "Globalstar"],
      rating: 4,
      numReviews: 88,
    },
    {
      name: "Globalstar 32\" Frameless HD Digital TV",
      brand: "Globalstar",
      category: byName("Home Entertainment"),
      price: 329000,
      stock: 37,
      sku: "GLOBALSTAR-32-INCH-FRAME",
      images: [ASSET_BASE + "/jumia/clean-tv32-a.webp"],
      description: "A frameless 32 inch HD digital LED — the thin bezel is unusual at this price. Free-to-air tuner built in, low power draw, and light enough to wall mount on plasterboard.",
      tags: ["Home Entertainment", "Globalstar", "express", "Express"],
      rating: 3.9,
      numReviews: 143,
    },
    {
      name: "Smartec 32\" HD LED Free-to-Air TV",
      brand: "Smartec",
      category: byName("Home Entertainment"),
      price: 307000,
      stock: 29,
      sku: "SMARTEC-32-INCH-HD-LED-T",
      images: [ASSET_BASE + "/jumia/tv-smartec32.webp"],
      description: "A straightforward 32 inch HD LED with a digital free-to-air tuner. No apps, no WiFi, nothing to slow down or stop being supported — which is exactly why some people prefer them.",
      tags: ["Home Entertainment", "Smartec"],
      rating: 3.8,
      numReviews: 96,
    },
    {
      name: "Mitech 43\" Frameless Android Smart TV",
      brand: "Mitech",
      category: byName("Home Entertainment"),
      price: 582000,
      stock: 17,
      sku: "MITECH-43-INCH-FRAMELESS",
      images: [ASSET_BASE + "/jumia/clean-tv43-c.webp"],
      description: "A 43 inch frameless Android TV with the free-to-air decoder built in — streaming apps and local channels from one box, without a separate decoder cluttering the shelf.",
      tags: ["Home Entertainment", "Mitech"],
      rating: 4,
      numReviews: 104,
    },
    {
      name: "Itel 32\" HD Free-to-Air TV",
      brand: "Itel",
      category: byName("Home Entertainment"),
      price: 292000,
      stock: 42,
      sku: "ITEL-32-INCH-HD-FREE-TO-",
      images: [ASSET_BASE + "/jumia/tv-itel32.webp"],
      description: "A 32 inch HD digital TV carrying a three-year warranty — unusually long at this price, and the main reason to pick it over the other budget 32s.",
      tags: ["Home Entertainment", "Itel", "express", "Express"],
      rating: 3.9,
      numReviews: 171,
    },
    {
      name: "SPARK 50×50cm Full Gas Standing Cooker",
      brand: "SPARK",
      category: byName("Kitchen"),
      price: 318000,
      stock: 23,
      sku: "SPARK-50X50-FULL-GAS-COO",
      images: [ASSET_BASE + "/jumia/cooker-spark5050.webp"],
      description: "A full gas cooker — four burners and a gas oven, running entirely off the cylinder. Nothing to plug in, so it keeps working right through a blackout. The cheapest way into a standing cooker with a real oven.",
      tags: ["Kitchen", "SPARK"],
      rating: 4,
      numReviews: 127,
    },
    {
      name: "Blueflame 60×60cm 3 Gas + 1 Electric Cooker",
      brand: "Blueflame",
      category: byName("Kitchen"),
      price: 900000,
      stock: 7,
      sku: "BLUEFLAME-60X60-3-GAS-1-",
      images: [ASSET_BASE + "/jumia/clean-cooker-wide.webp"],
      description: "The 60cm version of the Blueflame: three gas burners, one electric hotplate and a notably wider electric oven that takes a full baking tray. Made in Turkey, three-year warranty.",
      tags: ["Kitchen", "Blueflame", "Free installation"],
      isFeatured: true,
      rating: 4.5,
      numReviews: 149,
    },
    {
      name: "Roch 160L Double-Door Top Freezer Fridge",
      brand: "Roch",
      category: byName("Cooling"),
      price: 598000,
      stock: 14,
      sku: "ROCH-160L-DOUBLE-DOOR-FR",
      images: [ASSET_BASE + "/jumia/clean-fridge-small.webp"],
      description: "A 160 litre double-door defrost fridge in an inox finish that resists fingerprints better than plain steel. 142 net litres of usable space with a separate top freezer.",
      tags: ["Cooling", "Roch"],
      rating: 4.1,
      numReviews: 118,
    },
    {
      name: "ADH 120L Single-Door Refrigerator",
      brand: "ADH",
      category: byName("Cooling"),
      price: 413000,
      stock: 26,
      sku: "ADH-120L-SINGLE-DOOR-REF",
      images: [ASSET_BASE + "/jumia/clean-fridge-small.webp"],
      description: "A 120 litre single-door fridge with an internal freezer box, carrying a three-year warranty — considerably longer than most fridges at this size and price.",
      tags: ["Cooling", "ADH"],
      rating: 4,
      numReviews: 164,
    },
    {
      name: "Blueflame 90×60cm Diamond Cooker, 4 Gas + 2 Electric",
      brand: "Blueflame",
      category: byName("Kitchen"),
      price: 1889000,
      stock: 4,
      sku: "BLUEFLAME-90X60-DIAMOND-",
      images: [ASSET_BASE + "/jumia/clean-cooker-4burner.webp"],
      description: "The flagship: 90cm wide with four gas burners, two electric plates and an oven that swallows a full catering tray. Stainless inox throughout, made in Turkey, three-year warranty. For households that genuinely cook, or a small commercial kitchen.",
      tags: ["Kitchen", "Blueflame", "Free installation"],
      isFeatured: true,
      rating: 4.6,
      numReviews: 71,
    },
    {
      name: "Blueflame 60×60cm Diamond Cooker with Digital Timer",
      brand: "Blueflame",
      category: byName("Kitchen"),
      price: 1444000,
      stock: 6,
      sku: "BLUEFLAME-D6031-DIAMOND-",
      images: [ASSET_BASE + "/jumia/clean-cooker-inox.webp"],
      description: "The Diamond series adds a digital timer to the 60cm body — set the oven and it switches itself off. Three gas burners, one electric plate, and a silver finish that suits a modern fitted kitchen.",
      tags: ["Kitchen", "Blueflame", "Free installation"],
      rating: 4.5,
      numReviews: 58,
    },
    {
      name: "Blueflame 60×60cm Inox Cooker, 3 Gas + 1 Electric",
      brand: "Blueflame",
      category: byName("Kitchen"),
      price: 1130000,
      stock: 8,
      sku: "BLUEFLAME-60X60-INOX-COO",
      images: [ASSET_BASE + "/jumia/clean-cooker-inox.webp"],
      description: "The same 60cm layout in full stainless inox rather than enamel — better in a humid kitchen, and fingerprints wipe straight off. Three gas burners, one electric plate, electric oven below.",
      tags: ["Kitchen", "Blueflame", "Free installation"],
      rating: 4.4,
      numReviews: 94,
    },
    {
      name: "Blueflame 50×60cm Cooker, 3 Gas + 1 Hotplate",
      brand: "Blueflame",
      category: byName("Kitchen"),
      price: 756000,
      stock: 11,
      sku: "BLUEFLAME-NL6031-50X60-C",
      images: [ASSET_BASE + "/jumia/clean-cooker-steel.webp"],
      description: "Fifty centimetres wide but sixty deep, so you get a noticeably roomier oven without losing worktop space. The sensible middle option between the 50×50 and the full 60×60.",
      tags: ["Kitchen", "Blueflame"],
      rating: 4.3,
      numReviews: 112,
    },
    {
      name: "Blueflame 50×50cm Cooker, 2 Gas + 2 Electric",
      brand: "Blueflame",
      category: byName("Kitchen"),
      price: 670000,
      stock: 13,
      sku: "BLUEFLAME-C5022-2GAS-2EL",
      images: [ASSET_BASE + "/jumia/clean-cooker-wide.webp"],
      description: "Two gas burners and two electric hotplates, so half the hob keeps working whichever supply fails. A practical hedge when both the cylinder and the grid are unpredictable.",
      tags: ["Kitchen", "Blueflame"],
      rating: 4.2,
      numReviews: 87,
    },
    {
      name: "Blueflame 45L Electric Mini Oven",
      brand: "Blueflame",
      category: byName("Kitchen"),
      price: 289000,
      stock: 24,
      sku: "BLUEFLAME-45L-ELECTRIC-M",
      images: [ASSET_BASE + "/jumia/oven-blueflame45.webp"],
      description: "Forty-five litres of countertop oven with a round tray included — enough for a full cake, a tray of chapati or a roast chicken. The affordable route to baking when a standing cooker will not fit or cannot be afforded.",
      tags: ["Kitchen", "Blueflame", "express", "Express"],
      isFeatured: true,
      rating: 4.3,
      numReviews: 134,
    },
    {
      name: "Blueflame 35L Electric Mini Oven",
      brand: "Blueflame",
      category: byName("Kitchen"),
      price: 219000,
      stock: 31,
      sku: "BLUEFLAME-35L-ELECTRIC-M",
      images: [ASSET_BASE + "/jumia/oven-blueflame35.webp"],
      description: "A 35 litre mini oven for households that bake occasionally — cakes, chapati, roast potatoes — without committing counter space to the 45 litre model.",
      tags: ["Kitchen", "Blueflame", "express", "Express"],
      rating: 4.2,
      numReviews: 156,
    },
    {
      name: "Blueflame 25L Electric Mini Oven",
      brand: "Blueflame",
      category: byName("Kitchen"),
      price: 200000,
      stock: 36,
      sku: "BLUEFLAME-25L-ELECTRIC-M",
      images: [ASSET_BASE + "/jumia/oven-blueflame25.webp"],
      description: "Twenty-five litres — a genuine oven with a thermostat, small enough for a hostel room or an office kitchen. Toasts, bakes and grills without needing a gas connection.",
      tags: ["Kitchen", "Blueflame", "express", "Express"],
      rating: 4,
      numReviews: 98,
    },
    {
      name: "Blueflame 20L Digital Microwave with Auto-Cook",
      brand: "Blueflame",
      category: byName("Kitchen"),
      price: 225000,
      stock: 27,
      sku: "BLUEFLAME-20L-DIGITAL-MI",
      images: [ASSET_BASE + "/jumia/micro-blueflame20d.webp"],
      description: "A 20 litre digital microwave with preset auto-cook menus and a quick defrost programme. The digital panel gives finer control than dials, at a modest premium.",
      tags: ["Kitchen", "Blueflame", "express", "Express"],
      rating: 4.2,
      numReviews: 76,
    },
    {
      name: "Blueflame 20L Microwave Oven",
      brand: "Blueflame",
      category: byName("Kitchen"),
      price: 213000,
      stock: 33,
      sku: "BLUEFLAME-20L-MANUAL-MIC",
      images: [ASSET_BASE + "/jumia/micro-blueflame20.webp"],
      description: "The manual version of the 20 litre Blueflame: two dials, six power levels and a thirty-minute timer. Nothing to learn and no touch panel to stop responding.",
      tags: ["Kitchen", "Blueflame", "express", "Express"],
      rating: 4,
      numReviews: 143,
    },
    {
      name: "Blueflame O-300J Triple Gas Table Hob",
      brand: "Blueflame",
      category: byName("Kitchen"),
      price: 114000,
      stock: 48,
      sku: "BLUEFLAME-O300J-TRIPLE-G",
      images: [ASSET_BASE + "/jumia/hob-blueflame-o300j.webp"],
      description: "A three-burner gas table hob that sits on any counter and runs off a cylinder. No electricity, no installation — the practical choice for a rented room, an outdoor kitchen or a backup during long outages.",
      tags: ["Kitchen", "Blueflame", "express", "Express"],
      rating: 4.1,
      numReviews: 211,
    },
    {
      name: "Blueflame 50×50cm Desktop Gas Cooker",
      brand: "Blueflame",
      category: byName("Kitchen"),
      price: 179000,
      stock: 22,
      sku: "BLUEFLAME-DESKTOP-GAS-CO",
      images: [ASSET_BASE + "/jumia/cooker-blueflame-desktop.webp"],
      description: "A compact desktop unit combining gas burners with a small electric oven — the cheapest way to get both hob and oven without a standing cooker or any installation.",
      tags: ["Kitchen", "Blueflame", "express", "Express"],
      rating: 4,
      numReviews: 89,
    },
    {
      name: "Apple iPhone 17 Air — 256GB",
      brand: "Apple",
      category: byName("Phones & Tablets"),
      price: 4125000,
      stock: 6,
      sku: "APPLE-IPHONE-17-AIR-256G",
      images: [ASSET_BASE + "/jumia/phone-iphone17air.webp"],
      description: "The thinnest iPhone Apple has shipped, with a 6.5 inch display, 12GB of RAM and a 48MP main camera. Sealed retail stock with a one-year warranty honoured locally — not grey import.",
      tags: ["Phones & Tablets", "Apple", "express", "Express"],
      isFeatured: true,
      rating: 4.7,
      numReviews: 46,
    },
    {
      name: "Samsung Galaxy A07 4G — 64GB",
      brand: "Samsung",
      category: byName("Phones & Tablets"),
      price: 447000,
      stock: 24,
      sku: "SAMSUNG-GALAXY-A07-64GB",
      images: [ASSET_BASE + "/jumia/phone-samsung-a07.webp"],
      description: "A large-screen Samsung on a sensible budget: 6.7 inches, a 50MP camera and a 5000mAh battery that genuinely lasts two days on light use. Two-year Samsung warranty.",
      tags: ["Phones & Tablets", "Samsung", "express", "Express"],
      rating: 3.8,
      numReviews: 87,
    },
    {
      name: "Samsung Galaxy A06 4G — 64GB",
      brand: "Samsung",
      category: byName("Phones & Tablets"),
      price: 406000,
      stock: 31,
      sku: "SAMSUNG-GALAXY-A06-64GB",
      images: [ASSET_BASE + "/jumia/phone-samsung-a06.webp"],
      description: "The volume seller: a 6.7 inch Samsung with a 5000mAh battery and a 50MP camera, at a price most households can actually reach. Two-year warranty and parts available locally.",
      tags: ["Phones & Tablets", "Samsung", "express", "Express", "Bestseller"],
      rating: 4.4,
      numReviews: 213,
    },
    {
      name: "Oppo A55 — 8GB RAM, 256GB",
      brand: "Oppo",
      category: byName("Phones & Tablets"),
      price: 395000,
      stock: 19,
      sku: "OPPO-A55-256GB",
      images: [ASSET_BASE + "/jumia/clean-phone-blue.webp"],
      description: "Unusual memory for the money — 8GB of RAM and 256GB of storage under four hundred thousand. If you keep a lot of photos and music on the phone rather than in the cloud, this is the sensible buy.",
      tags: ["Phones & Tablets", "Oppo", "express", "Express"],
      rating: 4.1,
      numReviews: 124,
    },
    {
      name: "HP EliteBook 840 G8 — Core i7, 16GB, 512GB SSD",
      brand: "HP",
      category: byName("Computing"),
      price: 2118000,
      stock: 7,
      sku: "HP-ELITEBOOK-840-G8-I7",
      images: [ASSET_BASE + "/jumia/laptop-hp-elitebook.webp"],
      description: "A professionally renewed EliteBook: 11th-generation Core i7, 16GB of RAM and a 512GB SSD in a magnesium chassis built for daily carrying. Renewed means inspected, cleaned and tested — cosmetically near-new, at roughly half the price of sealed retail.",
      tags: ["Computing", "HP"],
      isFeatured: true,
      rating: 4.7,
      numReviews: 38,
    },
    {
      name: "Lenovo ThinkPad X1 Carbon — Core i7, 16GB, 512GB SSD",
      brand: "Lenovo",
      category: byName("Computing"),
      price: 1334000,
      stock: 9,
      sku: "LENOVO-THINKPAD-X1-CARBO",
      images: [ASSET_BASE + "/jumia/laptop-thinkpad-x1.webp"],
      description: "The X1 Carbon is the laptop journalists and consultants carry: a carbon-fibre chassis under 1.2kg with the best keyboard on any laptop. This is a renewed 7th-gen with Core i7, 16GB and a 512GB SSD.",
      tags: ["Computing", "Lenovo"],
      rating: 4.6,
      numReviews: 52,
    },
    {
      name: "HP ProBook 640 — Core i5, 16GB, 500GB",
      brand: "HP",
      category: byName("Computing"),
      price: 639000,
      stock: 14,
      sku: "HP-PROBOOK-640-I5-16GB",
      images: [ASSET_BASE + "/jumia/clean-laptop-silver.webp"],
      description: "Sixteen gigabytes of RAM for under 650,000 — the practical choice for a student or a small office. Grade A+ renewed, meaning it was inspected and shows minimal wear.",
      tags: ["Computing", "HP", "express", "Express"],
      rating: 3.9,
      numReviews: 167,
    },
    {
      name: "Dell Latitude 11\" Laptop with Bag & Mouse",
      brand: "Dell",
      category: byName("Computing"),
      price: 511000,
      stock: 17,
      sku: "DELL-LATITUDE-11-LAPTOP-",
      images: [ASSET_BASE + "/jumia/clean-laptop-bundle.webp"],
      description: "An 11 inch Latitude with 8GB of RAM, bundled with a carry bag and a mouse. Compact and light for coursework, email and browsing — and the cheapest way into a business-grade machine.",
      tags: ["Computing", "Dell", "express", "Express"],
      rating: 3.7,
      numReviews: 143,
    },
    {
      name: "Epson EcoTank L3210 All-in-One Printer",
      brand: "Epson",
      category: byName("Computing"),
      price: 879000,
      stock: 12,
      sku: "EPSON-ECOTANK-L3210-PRIN",
      images: [ASSET_BASE + "/jumia/printer-epson-l3210.webp"],
      description: "Refillable ink tanks instead of cartridges, which is the whole point: a set of bottles costs a fraction of cartridges and prints thousands of pages. Print, scan and copy in one A4 unit.",
      tags: ["Computing", "Epson"],
      isFeatured: true,
      rating: 4.5,
      numReviews: 96,
    },
    {
      name: "TCL 50\" 4K Android Google TV, Frameless",
      brand: "TCL",
      category: byName("Home Entertainment"),
      price: 1265000,
      stock: 10,
      sku: "TCL-50-INCH-4K-GOOGLE-TV",
      images: [ASSET_BASE + "/jumia/tv-tcl50.webp"],
      description: "A 50 inch frameless 4K panel running full Google TV with the AiPQ processor, plus Bluetooth and a built-in T2-S2 tuner for free-to-air. The size most sitting rooms actually want.",
      tags: ["Home Entertainment", "TCL"],
      isFeatured: true,
      rating: 4.5,
      numReviews: 74,
    },
    {
      name: "LG 2.1CH Soundbar S40T — 300W",
      brand: "LG",
      category: byName("Home Entertainment"),
      price: 798000,
      stock: 15,
      sku: "LG-SOUNDBAR-S40T-300W",
      images: [ASSET_BASE + "/jumia/soundbar-lg-s40t.webp"],
      description: "Every slim TV has thin, tinny speakers — there is no room inside for anything better. A 300W 2.1 soundbar with a wireless subwoofer fixes it in five minutes with one HDMI cable.",
      tags: ["Home Entertainment", "LG", "express", "Express"],
      rating: 4.4,
      numReviews: 61,
    },
    {
      name: "LG 9kg Front-Load Washing Machine",
      brand: "LG",
      category: byName("Laundry"),
      price: 2546000,
      stock: 5,
      sku: "LG-9KG-FRONT-LOAD-WASHIN",
      images: [ASSET_BASE + "/jumia/wash-lg-9kg.webp"],
      description: "LG inverter direct drive: the motor couples straight to the drum with no belt, so there is less to wear out and far less noise. Nine kilos, and the motor carries a ten-year warranty.",
      tags: ["Laundry", "LG", "Free installation"],
      rating: 4.7,
      numReviews: 58,
    },
    {
      name: "Midea Hot & Cold Water Dispenser",
      brand: "Midea",
      category: byName("Small Appliances"),
      price: 420000,
      stock: 16,
      sku: "MIDEA-HOT-COLD-WATER-DIS",
      images: [ASSET_BASE + "/jumia/dispenser-midea.webp"],
      description: "Hot and cold on tap from a standard 20 litre bottle, with 460W fast heating and a lower cabinet for storing cups or a spare bottle. Standard fitting in Ugandan offices and reception areas.",
      tags: ["Small Appliances", "Midea"],
      rating: 4.3,
      numReviews: 89,
    },
    {
      name: "Geepas 16\" Orbit Ceiling Fan",
      brand: "Geepas",
      category: byName("Cooling"),
      price: 208000,
      stock: 28,
      sku: "GEEPAS-16-INCH-ORBIT-CEI",
      images: [ASSET_BASE + "/jumia/fan-geepas-ceiling.webp"],
      description: "An orbit-style ceiling fan with genuinely wide oscillation, so it moves air across a whole room rather than one spot. Three speeds, ABS blades behind a metal guard, and only 60W.",
      tags: ["Cooling", "Geepas", "express", "Express"],
      rating: 4.1,
      numReviews: 112,
    },
    {
      name: "Digiwave 2-in-1 Steel Jar Blender, 500W",
      brand: "Digiwave",
      category: byName("Kitchen"),
      price: 82000,
      stock: 32,
      sku: "DIGIWAVE-2IN1-STEEL-JAR-",
      images: [ASSET_BASE + "/jumia/blend-digiwave.webp"],
      description: "A 1.5 litre stainless steel jar for wet blending plus a separate plastic grinder jar for dry spices and groundnuts. Steel will not crack or stain the way glass and plastic do.",
      tags: ["Kitchen", "Digiwave", "express", "Express"],
      rating: 4.2,
      numReviews: 134,
    },
  ];

  for (const p of products) await Product.create(p);

  console.log(`Seeded ${categories.length} categories and ${products.length} products (UGX).`);
  console.log("Admin login: admin@chikwafu.com / admin123");
  process.exit(0);
};

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
